    "#if __SIZEOF_POINTER__==4\n"
    "#if defined __OpenBSD__\n"
    "#define __SIZE_TYPE__ unsigned long\n"
    "#define __PTRDIFF_TYPE__ long\n"
    "#else\n"
    "#define __SIZE_TYPE__ unsigned int\n"
    "#define __PTRDIFF_TYPE__ int\n"
    "#endif\n"
    "#define __ILP32__ 1\n"
    "#define __INT64_TYPE__ long long\n"
    "#elif __SIZEOF_LONG__==4\n"
    "#define __SIZE_TYPE__ unsigned long long\n"
    "#define __PTRDIFF_TYPE__ long long\n"
    "#define __LLP64__ 1\n"
    "#define __INT64_TYPE__ long long\n"
    "#else\n"
    "#define __SIZE_TYPE__ unsigned long\n"
    "#define __PTRDIFF_TYPE__ long\n"
    "#define __LP64__ 1\n"
    "#if defined __linux__\n"
    "#define __INT64_TYPE__ long\n"
    "#else\n"
    "#define __INT64_TYPE__ long long\n"
    "#endif\n"
    "#endif\n"
    "#define __SIZEOF_INT__ 4\n"
    "#define __INT_MAX__ 0x7fffffff\n"
    "#if __SIZEOF_LONG__==4\n"
    "#define __LONG_MAX__ 0x7fffffffL\n"
    "#else\n"
    "#define __LONG_MAX__ 0x7fffffffffffffffL\n"
    "#endif\n"
    "#define __SIZEOF_LONG_LONG__ 8\n"
    "#define __LONG_LONG_MAX__ 0x7fffffffffffffffLL\n"
    "#define __CHAR_BIT__ 8\n"
    "#define __ORDER_LITTLE_ENDIAN__ 1234\n"
    "#define __ORDER_BIG_ENDIAN__ 4321\n"
    "#define __BYTE_ORDER__ __ORDER_LITTLE_ENDIAN__\n"
    "#if defined _WIN32\n"
    "#define __WCHAR_TYPE__ unsigned short\n"
    "#define __WINT_TYPE__ unsigned short\n"
    "#elif defined __linux__&&(defined __arm__||defined __aarch64__)\n"
    "#define __WCHAR_TYPE__ unsigned int\n"
    "#define __WINT_TYPE__ unsigned int\n"
    "#elif defined __linux__\n"
    "#define __WCHAR_TYPE__ int\n"
    "#define __WINT_TYPE__ unsigned int\n"
    "#else\n"
    "#define __WCHAR_TYPE__ int\n"
    "#define __WINT_TYPE__ int\n"
    "#endif\n"

    "#if!defined _WIN32\n"
    "#define __STDC_ISO_10646__ 201706L\n"
    "#endif\n"

    "#define __STDC_IEC_559__ 1\n"
    "#define __STDC_IEC_559_COMPLEX__ 1\n"
    "#define __GCC_IEC_559 2\n"
    "#define __GCC_IEC_559_COMPLEX 2\n"

    "#define __STDC_UTF_16__ 1\n"
    "#define __STDC_UTF_32__ 1\n"

    "#if defined _WIN32\n"
    "#define __declspec(x) __attribute__((x))\n"
    "#define __cdecl\n"

    "#elif defined __FreeBSD__\n"
    "#define __GNUC__ 9\n"
    "#define __GNUC_MINOR__ 3\n"
    "#define __GNUC_PATCHLEVEL__ 0\n"
    "#define __GNUC_STDC_INLINE__ 1\n"
    "#define __NO_TLS 1\n"
    "#define __RUNETYPE_INTERNAL 1\n"
    "#if __SIZEOF_POINTER__==8\n"
    "#define __SIZEOF_SIZE_T__ 8\n"
    "#define __SIZEOF_PTRDIFF_T__ 8\n"
    "#else\n"
    "#define __SIZEOF_SIZE_T__ 4\n"
    "#define __SIZEOF_PTRDIFF_T__ 4\n"
    "#endif\n"

    "#elif defined __FreeBSD_kernel__\n"

    "#elif defined __NetBSD__\n"
    "#define __GNUC__ 4\n"
    "#define __GNUC_MINOR__ 1\n"
    "#define __GNUC_PATCHLEVEL__ 0\n"
    "#define _Pragma(x)\n"
    "#define __ELF__ 1\n"
    "#if defined __aarch64__\n"
    "#define _LOCORE\n"
    "#endif\n"

    "#elif defined __OpenBSD__\n"
    "#define __GNUC__ 4\n"
    "#define _ANSI_LIBRARY 1\n"

    "#elif defined __APPLE__\n"
    "#define __GNUC__ 4\n"
    "#define __APPLE_CC__ 1\n"
    "#define __LITTLE_ENDIAN__ 1\n"
    "#define _DONT_USE_CTYPE_INLINE_ 1\n"

    "#define __FINITE_MATH_ONLY__ 0\n"
    "#define __FLT_MIN__ 1.17549435082228750797e-38F\n"
    "#define __DBL_MIN__ 2.2250738585072014e-308\n"
    "#if defined __aarch64__\n"
    "#define __LDBL_MIN__ 2.2250738585072014e-308L\n"
    "#else\n"
    "#define __LDBL_MIN__ 3.36210314311209350626e-4932L\n"
    "#endif\n"
    "#define _Float16 short unsigned int\n"

    "#elif defined __ANDROID__\n"
    "#define BIONIC_IOCTL_NO_SIGNEDNESS_OVERLOAD\n"
    "#define __ELF__ 1\n"

    "#elif defined __linux__\n"
    "#define __ELF__ 1\n"

    "#else\n"

    "#endif\n"

    "#ifndef __NetBSD__\n"
    "#define __UINTPTR_TYPE__ unsigned __PTRDIFF_TYPE__\n"
    "#define __INTPTR_TYPE__ __PTRDIFF_TYPE__\n"
    "#endif\n"
    "#define __INT8_TYPE__ signed char\n"
    "#define __UINT8_TYPE__ unsigned char\n"
    "#define __INT16_TYPE__ short\n"
    "#define __UINT16_TYPE__ unsigned short\n"
    "#define __INT32_TYPE__ int\n"
    "#define __UINT32_TYPE__ unsigned int\n"
    "#define __CHAR16_TYPE__ unsigned short\n"
    "#define __CHAR32_TYPE__ unsigned int\n"
    "#define __CHAR8_TYPE__ unsigned char\n"

    "#define __SCHAR_MAX__ 0x7f\n"
    "#define __SHRT_MAX__ 0x7fff\n"
    "#define __INT_MIN__ (-__INT_MAX__-1)\n"
    "#define __LONG_MIN__ (-__LONG_MAX__-1L)\n"
    "#define __LONG_LONG_MIN__ (-__LONG_LONG_MAX__-1LL)\n"

    "#define __INT8_TYPE__ signed char\n"
    "#define __UINT8_TYPE__ unsigned char\n"
    "#define __INT8_MAX__ 0x7f\n"
    "#define __UINT8_MAX__ 0xff\n"
    "#define __INT16_TYPE__ short int\n"
    "#define __UINT16_TYPE__ short unsigned int\n"
    "#define __INT16_MAX__ 0x7fff\n"
    "#define __UINT16_MAX__ 0xffff\n"
    "#define __INT32_MAX__ 0x7fffffff\n"
    "#define __UINT32_MAX__ 0xffffffffU\n"

    "#if __SIZEOF_LONG__==8&&defined __linux__\n"
    "#define __UINT64_TYPE__ long unsigned int\n"
    "#define __INT64_MAX__ 0x7fffffffffffffffL\n"
    "#define __UINT64_MAX__ 0xffffffffffffffffUL\n"
    "#else\n"
    "#define __UINT64_TYPE__ long long unsigned int\n"
    "#define __INT64_MAX__ 0x7fffffffffffffffLL\n"
    "#define __UINT64_MAX__ 0xffffffffffffffffULL\n"
    "#endif\n"

    "#define __INTMAX_TYPE__ __INT64_TYPE__\n"
    "#define __UINTMAX_TYPE__ __UINT64_TYPE__\n"
    "#define __INTMAX_MAX__ __INT64_MAX__\n"
    "#define __UINTMAX_MAX__ __UINT64_MAX__\n"

    "#define __INT_LEAST8_TYPE__ __INT8_TYPE__\n"
    "#define __UINT_LEAST8_TYPE__ __UINT8_TYPE__\n"
    "#define __INT_LEAST8_MAX__ __INT8_MAX__\n"
    "#define __UINT_LEAST8_MAX__ __UINT8_MAX__\n"
    "#define __INT_LEAST16_TYPE__ __INT16_TYPE__\n"
    "#define __UINT_LEAST16_TYPE__ __UINT16_TYPE__\n"
    "#define __INT_LEAST16_MAX__ __INT16_MAX__\n"
    "#define __UINT_LEAST16_MAX__ __UINT16_MAX__\n"
    "#define __INT_LEAST32_TYPE__ __INT32_TYPE__\n"
    "#define __UINT_LEAST32_TYPE__ __UINT32_TYPE__\n"
    "#define __INT_LEAST32_MAX__ __INT32_MAX__\n"
    "#define __UINT_LEAST32_MAX__ __UINT32_MAX__\n"
    "#define __INT_LEAST64_TYPE__ __INT64_TYPE__\n"
    "#define __UINT_LEAST64_TYPE__ __UINT64_TYPE__\n"
    "#define __INT_LEAST64_MAX__ __INT64_MAX__\n"
    "#define __UINT_LEAST64_MAX__ __UINT64_MAX__\n"

    "#define __INT_FAST8_TYPE__ signed char\n"
    "#define __UINT_FAST8_TYPE__ unsigned char\n"
    "#define __INT_FAST8_MAX__ __INT8_MAX__\n"
    "#define __UINT_FAST8_MAX__ __UINT8_MAX__\n"
    "#if __SIZEOF_LONG__==8&&defined __linux__\n"
    "#define __INT_FAST16_TYPE__ long int\n"
    "#define __UINT_FAST16_TYPE__ long unsigned int\n"
    "#define __INT_FAST32_TYPE__ long int\n"
    "#define __UINT_FAST32_TYPE__ long unsigned int\n"
    "#define __INT_FAST64_TYPE__ long int\n"
    "#define __UINT_FAST64_TYPE__ long unsigned int\n"
    "#define __INT_FAST16_MAX__ __INT64_MAX__\n"
    "#define __UINT_FAST16_MAX__ __UINT64_MAX__\n"
    "#define __INT_FAST32_MAX__ __INT64_MAX__\n"
    "#define __UINT_FAST32_MAX__ __UINT64_MAX__\n"
    "#define __INT_FAST64_MAX__ __INT64_MAX__\n"
    "#define __UINT_FAST64_MAX__ __UINT64_MAX__\n"
    "#else\n"
    "#define __INT_FAST16_TYPE__ int\n"
    "#define __UINT_FAST16_TYPE__ unsigned int\n"
    "#define __INT_FAST32_TYPE__ int\n"
    "#define __UINT_FAST32_TYPE__ unsigned int\n"
    "#define __INT_FAST64_TYPE__ __INT64_TYPE__\n"
    "#define __UINT_FAST64_TYPE__ __UINT64_TYPE__\n"
    "#define __INT_FAST16_MAX__ __INT32_MAX__\n"
    "#define __UINT_FAST16_MAX__ __UINT32_MAX__\n"
    "#define __INT_FAST32_MAX__ __INT32_MAX__\n"
    "#define __UINT_FAST32_MAX__ __UINT32_MAX__\n"
    "#define __INT_FAST64_MAX__ __INT64_MAX__\n"
    "#define __UINT_FAST64_MAX__ __UINT64_MAX__\n"
    "#endif\n"

    "#if __SIZEOF_PTRDIFF_T__==8\n"
    "#define __PTRDIFF_MAX__ 0x7fffffffffffffffL\n"
    "#else\n"
    "#define __PTRDIFF_MAX__ 0x7fffffff\n"
    "#endif\n"
    "#define __PTRDIFF_MIN__ (-__PTRDIFF_MAX__-1)\n"
    "#if __SIZEOF_SIZE_T__==8\n"
    "#define __SIZE_MAX__ 0xffffffffffffffffUL\n"
    "#else\n"
    "#define __SIZE_MAX__ 0xffffffffU\n"
    "#endif\n"

    "#if defined __linux__&&(defined __arm__||defined __aarch64__)\n"
    "#define __WCHAR_MAX__ 0xffffffffU\n"
    "#define __WCHAR_MIN__ 0U\n"
    "#else\n"
    "#define __WCHAR_MAX__ 0x7fffffff\n"
    "#define __WCHAR_MIN__ (-__WCHAR_MAX__-1)\n"
    "#endif\n"
    "#define __WINT_MAX__ 0xffffffffU\n"
    "#define __WINT_MIN__ 0U\n"

    "#define __SIG_ATOMIC_TYPE__ int\n"
    "#define __SIG_ATOMIC_MAX__ 0x7fffffff\n"
    "#define __SIG_ATOMIC_MIN__ (-__SIG_ATOMIC_MAX__-1)\n"

    "#define __BIGGEST_ALIGNMENT__ 16\n"
    "#define __FLT_EVAL_METHOD__ 0\n"

    "#define __FLT_RADIX__ 2\n"
    "#define __FLT_MANT_DIG__ 24\n"
    "#define __FLT_DIG__ 6\n"
    "#define __FLT_MIN_EXP__ (-125)\n"
    "#define __FLT_MIN_10_EXP__ (-37)\n"
    "#define __FLT_MAX_EXP__ 128\n"
    "#define __FLT_MAX_10_EXP__ 38\n"
    "#define __FLT_MAX__ 3.40282346638528859811704183484516925e+38F\n"
    "#define __FLT_EPSILON__ 1.19209289550781250000000000000000000e-7F\n"
    "#define __FLT_DENORM_MIN__ 1.40129846432481707092372958328991613e-45F\n"
    "#define __FLT_HAS_DENORM__ 1\n"
    "#define __FLT_HAS_INFINITY__ 1\n"
    "#define __FLT_HAS_QUIET_NAN__ 1\n"

    "#define __DBL_MANT_DIG__ 53\n"
    "#define __DBL_DIG__ 15\n"
    "#define __DBL_MIN_EXP__ (-1021)\n"
    "#define __DBL_MIN_10_EXP__ (-307)\n"
    "#define __DBL_MAX_EXP__ 1024\n"
    "#define __DBL_MAX_10_EXP__ 308\n"
    "#define __DBL_MAX__ ((double)1.79769313486231570814527423731704357e+308L)\n"
    "#define __DBL_EPSILON__ ((double)2.22044604925031308084726333618164062e-16L)\n"
    "#define __DBL_DENORM_MIN__ ((double)4.94065645841246544176568792868221372e-324L)\n"
    "#define __DBL_HAS_DENORM__ 1\n"
    "#define __DBL_HAS_INFINITY__ 1\n"
    "#define __DBL_HAS_QUIET_NAN__ 1\n"

    "#if defined __x86_64__||defined __i386__\n"
    "#define __LDBL_MANT_DIG__ 64\n"
    "#define __LDBL_DIG__ 18\n"
    "#define __LDBL_MIN_EXP__ (-16381)\n"
    "#define __LDBL_MIN_10_EXP__ (-4931)\n"
    "#define __LDBL_MAX_EXP__ 16384\n"
    "#define __LDBL_MAX_10_EXP__ 4932\n"
    "#define __LDBL_MAX__ 1.18973149535723176502126385303097021e+4932L\n"
    "#define __LDBL_EPSILON__ 1.08420217248550443400745280086994171e-19L\n"
    "#define __LDBL_DENORM_MIN__ 3.64519953188247460252840593361941982e-4951L\n"
    "#else\n"
    "#define __LDBL_MANT_DIG__ __DBL_MANT_DIG__\n"
    "#define __LDBL_DIG__ __DBL_DIG__\n"
    "#define __LDBL_MIN_EXP__ __DBL_MIN_EXP__\n"
    "#define __LDBL_MIN_10_EXP__ __DBL_MIN_10_EXP__\n"
    "#define __LDBL_MAX_EXP__ __DBL_MAX_EXP__\n"
    "#define __LDBL_MAX_10_EXP__ __DBL_MAX_10_EXP__\n"
    "#define __LDBL_MAX__ __DBL_MAX__\n"
    "#define __LDBL_EPSILON__ __DBL_EPSILON__\n"
    "#define __LDBL_DENORM_MIN__ __DBL_DENORM_MIN__\n"
    "#endif\n"
    "#define __LDBL_HAS_DENORM__ 1\n"
    "#define __LDBL_HAS_INFINITY__ 1\n"
    "#define __LDBL_HAS_QUIET_NAN__ 1\n"

    "#define __ATOMIC_RELAXED 0\n"
    "#define __ATOMIC_CONSUME 1\n"
    "#define __ATOMIC_ACQUIRE 2\n"
    "#define __ATOMIC_RELEASE 3\n"
    "#define __ATOMIC_ACQ_REL 4\n"
    "#define __ATOMIC_SEQ_CST 5\n"

    "#if!defined _WIN32\n"
    "#define __REDIRECT(name,proto,alias) name proto __asm__(#alias)\n"
    "#define __REDIRECT_NTH(name,proto,alias) name proto __asm__(#alias)__THROW\n"
    "#define __REDIRECT_NTHNL(name,proto,alias) name proto __asm__(#alias)__THROWNL\n"
    "#endif\n"

    "#define __PRETTY_FUNCTION__ __FUNCTION__\n"
    "#define __has_builtin(x) 0\n"
    "#define __has_feature(x) 0\n"
    "#define __has_attribute(x) 0\n"
    "#define _Nonnull\n"
    "#define _Nullable\n"
    "#define _Nullable_result\n"
    "#define _Null_unspecified\n"

    "#ifndef __MCC_PP__\n"

    "typedef char __mcc_char_t;\n"
    "typedef signed char __mcc_schar_t;\n"
    "typedef unsigned char __mcc_uchar_t;\n"
    "typedef short __mcc_short_t;\n"
    "typedef unsigned short __mcc_ushort_t;\n"
    "typedef int __mcc_int_t;\n"
    "typedef unsigned int __mcc_uint_t;\n"
    "typedef long __mcc_long_t;\n"
    "typedef unsigned long __mcc_ulong_t;\n"
    "typedef long long __mcc_llong_t;\n"
    "typedef unsigned long long __mcc_ullong_t;\n"
    "typedef float __mcc_float_t;\n"
    "typedef double __mcc_double_t;\n"
    "typedef long double __mcc_ldouble_t;\n"
    "typedef __SIZE_TYPE__ __mcc_size_t;\n"

    "#define __builtin_offsetof(type,field) ((__mcc_size_t)&((type*)0)->field)\n"
    "#define __builtin_extract_return_addr(x) x\n"
    "#define __builtin_frob_return_addr(x) x\n"
    "#define __builtin_memcpy_inline(d,s,n) __builtin_memcpy((d),(s),(n))\n"
    "#define __builtin_memset_inline(d,c,n) __builtin_memset((d),(c),(n))\n"
    "#define __builtin_memmove_inline(d,s,n) __builtin_memmove((d),(s),(n))\n"
    "#define __sync_fetch_and_add(p,v) __atomic_fetch_add((p),(v),__ATOMIC_SEQ_CST)\n"
    "#define __sync_fetch_and_sub(p,v) __atomic_fetch_sub((p),(v),__ATOMIC_SEQ_CST)\n"
    "#define __sync_fetch_and_or(p,v) __atomic_fetch_or((p),(v),__ATOMIC_SEQ_CST)\n"
    "#define __sync_fetch_and_and(p,v) __atomic_fetch_and((p),(v),__ATOMIC_SEQ_CST)\n"
    "#define __sync_fetch_and_xor(p,v) __atomic_fetch_xor((p),(v),__ATOMIC_SEQ_CST)\n"
    "#define __sync_add_and_fetch(p,v) (__atomic_fetch_add((p),(v),__ATOMIC_SEQ_CST)+(v))\n"
    "#define __sync_sub_and_fetch(p,v) (__atomic_fetch_sub((p),(v),__ATOMIC_SEQ_CST)-(v))\n"
    "#define __sync_or_and_fetch(p,v) (__atomic_fetch_or((p),(v),__ATOMIC_SEQ_CST)|(v))\n"
    "#define __sync_and_and_fetch(p,v) (__atomic_fetch_and((p),(v),__ATOMIC_SEQ_CST)&(v))\n"
    "#define __sync_xor_and_fetch(p,v) (__atomic_fetch_xor((p),(v),__ATOMIC_SEQ_CST)^(v))\n"
    "#define __sync_bool_compare_and_swap(p,o,n) __extension__({__typeof__(*(p))__o=(o),__n=(n);__atomic_compare_exchange((p),&__o,&__n,0,__ATOMIC_SEQ_CST,__ATOMIC_SEQ_CST);})\n"
    "#define __sync_val_compare_and_swap(p,o,n) __extension__({__typeof__(*(p))__o=(o),__n=(n);__atomic_compare_exchange((p),&__o,&__n,0,__ATOMIC_SEQ_CST,__ATOMIC_SEQ_CST);__o;})\n"
    "#define __sync_lock_test_and_set(p,v) __extension__({__typeof__(*(p))__v=(v),__o;__atomic_exchange((p),&__v,&__o,__ATOMIC_SEQ_CST);__o;})\n"
    "#define __sync_lock_release(p) __extension__({__typeof__(*(p))__z=0;__atomic_store((p),&__z,__ATOMIC_SEQ_CST);})\n"
    "#define __sync_synchronize() __extension__({volatile __mcc_int_t __mcc_bar=0;(void)__atomic_fetch_add(&__mcc_bar,0,__ATOMIC_SEQ_CST);(void)0;})\n"
    "#define __atomic_load_n(p,o) __extension__({__typeof__(*(p))__r;__atomic_load((p),&__r,(o));__r;})\n"
    "#define __atomic_store_n(p,v,o) __extension__({__typeof__(*(p))__v=(v);__atomic_store((p),&__v,(o));})\n"
    "#define __atomic_exchange_n(p,v,o) __extension__({__typeof__(*(p))__v=(v),__r;__atomic_exchange((p),&__v,&__r,(o));__r;})\n"
    "#define __atomic_compare_exchange_n(p,e,d,w,s,f) __extension__({__typeof__(*(p))__d=(d);__atomic_compare_exchange((p),(e),&__d,(w),(s),(f));})\n"

    "#if!defined __linux__&&!defined _WIN32\n"
    "#if defined __APPLE__\n"
    "#define __builtin_flt_rounds() 1\n"
    "#define __builtin_bzero(p,ignored_size) bzero(p,sizeof(*(p)))\n"
    "#endif\n"
    "#endif\n"
    "#ifndef __builtin_nansf\n"
    "#define __builtin_nansf(s) (0.0f/0.0f)\n"
    "#endif\n"
    "#ifndef __builtin_nans\n"
    "#define __builtin_nans(s) (0.0/0.0)\n"
    "#endif\n"
    "#ifndef __builtin_nansl\n"
    "#define __builtin_nansl(s) (0.0L/0.0L)\n"
    "#endif\n"
    "#define __builtin_isnan(x) ((x)!=(x))\n"
    "#define __builtin_isnanf(x) __builtin_isnan(x)\n"
    "#define __builtin_isnanl(x) __builtin_isnan(x)\n"
    "#define __builtin_annotation(x,...) (x)\n"
    "#define __builtin_creal(z) (__real__(double _Complex)(z))\n"
    "#define __builtin_crealf(z) (__real__(float _Complex)(z))\n"
    "#define __builtin_creall(z) (__real__(long double _Complex)(z))\n"
    "#define __builtin_cimag(z) (__imag__(double _Complex)(z))\n"
    "#define __builtin_cimagf(z) (__imag__(float _Complex)(z))\n"
    "#define __builtin_cimagl(z) (__imag__(long double _Complex)(z))\n"
    "#define __builtin_conj(z) __builtin_complex(__builtin_creal(z),-__builtin_cimag(z))\n"
    "#define __builtin_conjf(z) __builtin_complex(__builtin_crealf(z),-__builtin_cimagf(z))\n"
    "#define __builtin_conjl(z) __builtin_complex(__builtin_creall(z),-__builtin_cimagl(z))\n"
    "#define __builtin_isinf(x) ((x)==__builtin_inf()||(x)==-__builtin_inf())\n"
    "#define __builtin_isfinite(x) (!__builtin_isnan(x)&&!__builtin_isinf(x))\n"
    "#define __builtin_isunordered(a,b) (__builtin_isnan(a)||__builtin_isnan(b))\n"
    "#define __builtin_isgreater(a,b) (!__builtin_isunordered(a,b)&&(a)>(b))\n"
    "#define __builtin_isgreaterequal(a,b) (!__builtin_isunordered(a,b)&&(a)>=(b))\n"
    "#define __builtin_isless(a,b) (!__builtin_isunordered(a,b)&&(a)<(b))\n"
    "#define __builtin_islessequal(a,b) (!__builtin_isunordered(a,b)&&(a)<=(b))\n"
    "#define __builtin_islessgreater(a,b) (!__builtin_isunordered(a,b)&&((a)<(b)||(a)>(b)))\n"
    "#define __builtin_fabsf(x) ((__mcc_float_t)((x)<=0?0.0f-(x):(x)))\n"
    "#define __builtin_fabs(x) ((__mcc_double_t)((x)<=0?0.0-(x):(x)))\n"
    "#define __builtin_fabsl(x) ((__mcc_ldouble_t)((x)<=0?0.0L-(x):(x)))\n"
    "#define __builtin_abs(x) ((__mcc_int_t)((x)<0?-(x):(x)))\n"
    "#define __builtin_labs(x) ((__mcc_long_t)((x)<0?-(x):(x)))\n"
    "#define __builtin_llabs(x) ((__mcc_llong_t)((x)<0?-(x):(x)))\n"
    "#define __builtin_copysignf(x,y) (__builtin_signbit(y)?-__builtin_fabsf(x):__builtin_fabsf(x))\n"
    "#define __builtin_copysign(x,y) (__builtin_signbit(y)?-__builtin_fabs(x):__builtin_fabs(x))\n"
    "#define __builtin_copysignl(x,y) (__builtin_signbit(y)?-__builtin_fabsl(x):__builtin_fabsl(x))\n"
    "#ifndef __FLT_MIN__\n"
    "#define __FLT_MIN__ 1.17549435082228750797e-38F\n"
    "#endif\n"
    "#ifndef __DBL_MIN__\n"
    "#define __DBL_MIN__ 2.2250738585072014e-308\n"
    "#endif\n"
    "#ifndef __LDBL_MIN__\n"
    "#if defined _WIN32||defined __arm__||(defined __aarch64__&&(defined __APPLE__||defined _WIN32))\n"
    "#define __LDBL_MIN__ 2.2250738585072014e-308L\n"
    "#else\n"
    "#define __LDBL_MIN__ 3.36210314311209350626e-4932L\n"
    "#endif\n"
    "#endif\n"
    "#define __builtin_isnormal(x) (__builtin_isfinite(x)&&(x)!=0&&_Generic((x),__mcc_float_t:__builtin_fabsf(x)>=__FLT_MIN__,__mcc_ldouble_t:__builtin_fabsl(x)>=__LDBL_MIN__,default:__builtin_fabs(x)>=__DBL_MIN__))\n"
    "#define __builtin_fpclassify(nan,inf,norm,sub,zero,x) (__builtin_isnan(x)?(nan):__builtin_isinf(x)?(inf):(x)==0?(zero):__builtin_isnormal(x)?(norm):(sub))\n"

    "#if defined __x86_64__&&!defined _WIN32\n"
    "#define __SIZEOF_INT128__ 16\n"
    "typedef __int128 __int128_t;\n"
    "typedef unsigned __int128 __uint128_t;\n"
    "typedef __int128 __mcc_int128_t;\n"
    "typedef unsigned __int128 __mcc_uint128_t;\n"
    "#else\n"
    "struct __uint128__{char x[16];}__attribute((__aligned__(16)));\n"
    "#define __int128_t struct __uint128__\n"
    "#define __uint128_t struct __uint128__\n"
    "#endif\n"

    "#if defined __x86_64__\n"
    "#if!defined _WIN32\n"
    "typedef struct __va_list_tag{\n"
    "unsigned gp_offset,fp_offset;\n"
    "union{\n"
    "unsigned overflow_offset;\n"
    "char*overflow_arg_area;\n"
    "};\n"
    "char*reg_save_area;\n"
    "}__builtin_va_list[1];\n"

    "void*__va_arg(__builtin_va_list ap,int arg_type,int size,int align);\n"
    "static __inline void*__va_arg_inline(__builtin_va_list ap,int arg_type,int size,int align){\n"
    "size=(size+7)&~7;\n"
    "align=(align+7)&~7;\n"
    "if(arg_type==0){\n"
    "if(ap->gp_offset+size<=48){\n"
    "ap->gp_offset+=size;\n"
    "return ap->reg_save_area+ap->gp_offset-size;\n"
    "}\n"
    "}else if(arg_type==1){\n"
    "if(ap->fp_offset<128+48){\n"
    "ap->fp_offset+=16;\n"
    "if(size==8)\n"
    "return ap->reg_save_area+ap->fp_offset-16;\n"
    "if(ap->fp_offset<128+48){\n"
    "*(long long*)(ap->reg_save_area+ap->fp_offset-8)=\n"
    "*(long long*)(ap->reg_save_area+ap->fp_offset);\n"
    "ap->fp_offset+=16;\n"
    "return ap->reg_save_area+ap->fp_offset-32;\n"
    "}\n"
    "}\n"
    "}\n"
    "ap->overflow_arg_area+=size;\n"
    "ap->overflow_arg_area=(char*)((long long)(ap->overflow_arg_area+align-1)&-align);\n"
    "return ap->overflow_arg_area-size;\n"
    "}\n"
    "#define __builtin_va_start(ap,last) (*(ap)=*(struct __va_list_tag*)((__mcc_char_t*)__builtin_frame_address(0)-24))\n"
    "#define __builtin_va_arg(ap,t) (*(t*)(__va_arg_inline(ap,__builtin_va_arg_types(t),sizeof(t),__alignof__(t))))\n"
    "#define __builtin_va_copy(dest,src) (*(dest)=*(src))\n"

    "#else\n"
    "typedef char*__builtin_va_list;\n"
    "#define __builtin_va_arg(ap,t) ((sizeof(t)>8||(sizeof(t)&(sizeof(t)-1)))?**(t**)((ap+=8)-8):*(t*)((ap+=8)-8))\n"
    "#endif\n"

    "#elif defined __arm__\n"
    "typedef char*__builtin_va_list;\n"
    "#define _mcc_alignof(type) ((__mcc_int_t)&((struct{__mcc_char_t c;type x;}*)0)->x)\n"
    "#define _mcc_align(addr,type) (((__mcc_uint_t)addr+_mcc_alignof(type)-1)&~(_mcc_alignof(type)-1))\n"
    "#define __builtin_va_start(ap,last) (ap=((__mcc_char_t*)&(last))+((sizeof(last)+3)&~3))\n"
    "#define __builtin_va_arg(ap,type) (ap=(void*)((_mcc_align(ap,type)+sizeof(type)+3)&~3),*(type*)(ap-((sizeof(type)+3)&~3)))\n"

    "#elif defined __aarch64__\n"
    "#if defined _WIN32\n"
    "typedef char*__builtin_va_list;\n"
    "#elif defined __APPLE__\n"
    "typedef struct{\n"
    "void*__stack;\n"
    "}__builtin_va_list;\n"

    "#else\n"
    "typedef struct{\n"
    "void*__stack,*__gr_top,*__vr_top;\n"
    "int __gr_offs,__vr_offs;\n"
    "}__builtin_va_list;\n"

    "#endif\n"
    "#elif defined __riscv\n"
    "typedef char*__builtin_va_list;\n"
    "#define __va_reg_size (__riscv_xlen>>3)\n"
    "#define _mcc_align(addr,type) (((__mcc_ulong_t)addr+__alignof__(type)-1)&-(__alignof__(type)))\n"
    "#define __builtin_va_arg(ap,type) (*(sizeof(type)>(2*__va_reg_size)?*(type**)((ap+=__va_reg_size)-__va_reg_size):(ap=(va_list)(_mcc_align(ap,type)+(sizeof(type)+__va_reg_size-1)&-__va_reg_size),(type*)(ap-((sizeof(type)+__va_reg_size-1)&-__va_reg_size)))))\n"

    "#else\n"
    "typedef char*__builtin_va_list;\n"
    "#define __builtin_va_start(ap,last) (ap=((__mcc_char_t*)&(last))+((sizeof(last)+3)&~3))\n"
    "#define __builtin_va_arg(ap,t) (*(t*)((ap+=(sizeof(t)+3)&~3)-((sizeof(t)+3)&~3)))\n"

    "#endif\n"
    "#define __builtin_va_end(ap) (void)(ap)\n"
    "#ifndef __builtin_va_copy\n"
    "#define __builtin_va_copy(dest,src) (dest)=(src)\n"
    "#endif\n"

    "#ifdef __leading_underscore\n"
    "#define __RENAME(X) __asm__(\"_\"X)\n"
    "#else\n"
    "#define __RENAME(X) __asm__(X)\n"
    "#endif\n"

    "#ifdef __MCC_BCHECK__\n"
    "#define __BUILTINBC(ret,name,params) ret __builtin_##name params __RENAME(\"__bound_\"#name);\n"
    "#define __BOUND(ret,name,params) ret name params __RENAME(\"__bound_\"#name);\n"
    "#else\n"
    "#define __BUILTINBC(ret,name,params) ret __builtin_##name params __RENAME(#name);\n"
    "#define __BOUND(ret,name,params)\n"
    "#endif\n"
    "#define __BOTH(ret,name,params) __BUILTINBC(ret,name,params)__BOUND(ret,name,params)\n"
    "#define __BUILTIN(ret,name,params) ret __builtin_##name params __RENAME(#name);\n"

    "__BOTH(void*,memcpy,(void*,const void*,__SIZE_TYPE__))\n"
    "__BOTH(void*,memmove,(void*,const void*,__SIZE_TYPE__))\n"
    "__BOTH(void*,memset,(void*,int,__SIZE_TYPE__))\n"
    "__BOTH(int,memcmp,(const void*,const void*,__SIZE_TYPE__))\n"
    "__BOTH(__SIZE_TYPE__,strlen,(const char*))\n"
    "__BOTH(char*,strcpy,(char*,const char*))\n"
    "__BOTH(char*,strncpy,(char*,const char*,__SIZE_TYPE__))\n"
    "__BOTH(int,strcmp,(const char*,const char*))\n"
    "__BOTH(int,strncmp,(const char*,const char*,__SIZE_TYPE__))\n"
    "__BOTH(char*,strcat,(char*,const char*))\n"
    "__BOTH(char*,strncat,(char*,const char*,__SIZE_TYPE__))\n"
    "__BOTH(char*,strchr,(const char*,int))\n"
    "__BOTH(char*,strrchr,(const char*,int))\n"
    "__BOTH(char*,strdup,(const char*))\n"
    "#if defined __ARM_EABI__\n"
    "__BOUND(void*,__aeabi_memcpy,(void*,const void*,__SIZE_TYPE__))\n"
    "__BOUND(void*,__aeabi_memmove,(void*,const void*,__SIZE_TYPE__))\n"
    "__BOUND(void*,__aeabi_memmove4,(void*,const void*,__SIZE_TYPE__))\n"
    "__BOUND(void*,__aeabi_memmove8,(void*,const void*,__SIZE_TYPE__))\n"
    "__BOUND(void*,__aeabi_memset,(void*,int,__SIZE_TYPE__))\n"
    "#endif\n"

    "#if defined __linux__||defined __APPLE__\n"
    "#define __MAYBE_REDIR __BUILTIN\n"
    "#else\n"
    "#define __MAYBE_REDIR __BOTH\n"
    "#endif\n"
    "__MAYBE_REDIR(void*,malloc,(__SIZE_TYPE__))\n"
    "__MAYBE_REDIR(void*,realloc,(void*,__SIZE_TYPE__))\n"
    "__MAYBE_REDIR(void*,calloc,(__SIZE_TYPE__,__SIZE_TYPE__))\n"
    "__MAYBE_REDIR(void*,memalign,(__SIZE_TYPE__,__SIZE_TYPE__))\n"
    "__MAYBE_REDIR(void,free,(void*))\n"
    "__BOTH(void*,alloca,(__SIZE_TYPE__))\n"
    "void*alloca(__SIZE_TYPE__);\n"
    "__BUILTIN(void,abort,(void))\n"
    "__BOUND(void,longjmp,())\n"
    "#if!defined _WIN32\n"
    "__BOUND(void*,mmap,())\n"
    "__BOUND(int,munmap,())\n"
    "#endif\n"
    "__BUILTIN(int,printf,(const char*,...))\n"
    "__BUILTIN(int,fprintf,(void*,const char*,...))\n"
    "__BUILTIN(int,sprintf,(char*,const char*,...))\n"
    "__BUILTIN(int,snprintf,(char*,__SIZE_TYPE__,const char*,...))\n"
    "__BUILTIN(int,vsprintf,(char*,const char*,__builtin_va_list))\n"
    "__BUILTIN(int,vsnprintf,(char*,__SIZE_TYPE__,const char*,__builtin_va_list))\n"
    "__BUILTIN(int,puts,(const char*))\n"
    "__BUILTIN(int,fputs,(const char*,void*))\n"
    "__BUILTIN(int,fputc,(int,void*))\n"
    "__BUILTIN(int,putchar,(int))\n"
    "__BUILTIN(__SIZE_TYPE__,fwrite,(const void*,__SIZE_TYPE__,__SIZE_TYPE__,void*))\n"
    "__BUILTIN(int,fprintf_unlocked,(void*,const char*,...))\n"
    "__BUILTIN(int,fputs_unlocked,(const char*,void*))\n"
    "__BUILTIN(int,printf_unlocked,(const char*,...))\n"
    "__BUILTIN(void,exit,(int))\n"
    "__BUILTIN(void*,memchr,(const void*,int,__SIZE_TYPE__))\n"
    "__BUILTIN(void*,mempcpy,(void*,const void*,__SIZE_TYPE__))\n"
    "__BUILTIN(char*,stpcpy,(char*,const char*))\n"
    "__BUILTIN(char*,stpncpy,(char*,const char*,__SIZE_TYPE__))\n"
    "__BUILTIN(__SIZE_TYPE__,strnlen,(const char*,__SIZE_TYPE__))\n"
    "__BUILTIN(char*,strstr,(const char*,const char*))\n"
    "__BUILTIN(__SIZE_TYPE__,strspn,(const char*,const char*))\n"
    "__BUILTIN(__SIZE_TYPE__,strcspn,(const char*,const char*))\n"
    "__BUILTIN(char*,strpbrk,(const char*,const char*))\n"
    "__BUILTIN(void,bcopy,(const void*,void*,__SIZE_TYPE__))\n"
    "__BUILTIN(int,bcmp,(const void*,const void*,__SIZE_TYPE__))\n"
    "__BUILTIN(char*,index,(const char*,int))\n"
    "__BUILTIN(char*,rindex,(const char*,int))\n"
    "#ifndef __builtin_bzero\n"
    "__BUILTIN(void,bzero,(void*,__SIZE_TYPE__))\n"
    "#endif\n"
    "__BUILTIN(void*,aligned_alloc,(__SIZE_TYPE__,__SIZE_TYPE__))\n"
    "__BUILTIN(double,cabs,(double _Complex))\n"
    "__BUILTIN(float,cabsf,(float _Complex))\n"
    "__BUILTIN(long double,cabsl,(long double _Complex))\n"
    "__BUILTIN(int,strcasecmp,(const char*,const char*))\n"
    "__BUILTIN(int,strncasecmp,(const char*,const char*,__SIZE_TYPE__))\n"
    "__BUILTIN(char*,strndup,(const char*,__SIZE_TYPE__))\n"
    "#undef __BUILTINBC\n"
    "#undef __BUILTIN\n"
    "#undef __BOUND\n"
    "#undef __BOTH\n"
    "#undef __MAYBE_REDIR\n"
    "#undef __RENAME\n"

    "extern void __chk_fail(void)__attribute__((noreturn));\n"

    "static __inline void*__builtin___memcpy_chk(void*dst,const void*src,__mcc_size_t len,__mcc_size_t dstlen){\n"
    "if(dstlen!=(__mcc_size_t)-1&&len>dstlen)\n"
    "__chk_fail();\n"
    "return __builtin_memcpy(dst,src,len);\n"
    "}\n"
    "static __inline void*__builtin___mempcpy_chk(void*dst,const void*src,__mcc_size_t len,__mcc_size_t dstlen){\n"
    "if(dstlen!=(__mcc_size_t)-1&&len>dstlen)\n"
    "__chk_fail();\n"
    "return __builtin_mempcpy(dst,src,len);\n"
    "}\n"
    "static __inline void*__builtin___memmove_chk(void*dst,const void*src,__mcc_size_t len,__mcc_size_t dstlen){\n"
    "if(dstlen!=(__mcc_size_t)-1&&len>dstlen)\n"
    "__chk_fail();\n"
    "return __builtin_memmove(dst,src,len);\n"
    "}\n"
    "static __inline void*__builtin___memset_chk(void*dst,int val,__mcc_size_t len,__mcc_size_t dstlen){\n"
    "if(dstlen!=(__mcc_size_t)-1&&len>dstlen)\n"
    "__chk_fail();\n"
    "return __builtin_memset(dst,val,len);\n"
    "}\n"
    "static __inline char*__builtin___strcpy_chk(char*dst,const char*src,__mcc_size_t dstlen){\n"
    "__mcc_size_t len=__builtin_strlen(src)+1;\n"
    "if(dstlen!=(__mcc_size_t)-1&&len>dstlen)\n"
    "__chk_fail();\n"
    "return __builtin_strcpy(dst,src);\n"
    "}\n"
    "static __inline char*__builtin___stpcpy_chk(char*dst,const char*src,__mcc_size_t dstlen){\n"
    "__mcc_size_t len=__builtin_strlen(src)+1;\n"
    "if(dstlen!=(__mcc_size_t)-1&&len>dstlen)\n"
    "__chk_fail();\n"
    "return __builtin_stpcpy(dst,src);\n"
    "}\n"
    "static __inline char*__builtin___strcat_chk(char*dst,const char*src,__mcc_size_t dstlen){\n"
    "__mcc_size_t dl=__builtin_strlen(dst);\n"
    "__mcc_size_t sl=__builtin_strlen(src);\n"
    "if(dstlen!=(__mcc_size_t)-1&&dl+sl+1>dstlen)\n"
    "__chk_fail();\n"
    "return __builtin_strcat(dst,src);\n"
    "}\n"
    "static __inline char*__builtin___strncpy_chk(char*dst,const char*src,__mcc_size_t len,__mcc_size_t dstlen){\n"
    "if(dstlen!=(__mcc_size_t)-1&&len>dstlen)\n"
    "__chk_fail();\n"
    "return __builtin_strncpy(dst,src,len);\n"
    "}\n"
    "static __inline char*__builtin___stpncpy_chk(char*dst,const char*src,__mcc_size_t len,__mcc_size_t dstlen){\n"
    "if(dstlen!=(__mcc_size_t)-1&&len>dstlen)\n"
    "__chk_fail();\n"
    "return __builtin_stpncpy(dst,src,len);\n"
    "}\n"
    "static __inline char*__builtin___strncat_chk(char*dst,const char*src,__mcc_size_t len,__mcc_size_t dstlen){\n"
    "__mcc_size_t dl=__builtin_strlen(dst);\n"
    "__mcc_size_t sl=__builtin_strlen(src);\n"
    "__mcc_size_t addlen=sl<len?sl:len;\n"
    "if(dstlen!=(__mcc_size_t)-1&&dl+addlen+1>dstlen)\n"
    "__chk_fail();\n"
    "return __builtin_strncat(dst,src,len);\n"
    "}\n"
    "static __inline int __builtin___vsnprintf_chk(char*s,__mcc_size_t n,int flag,__mcc_size_t slen,const char*fmt,__builtin_va_list ap){\n"
    "(void)flag;\n"
    "if(slen!=(__mcc_size_t)-1&&n>slen)\n"
    "__chk_fail();\n"
    "return __builtin_vsnprintf(s,n,fmt,ap);\n"
    "}\n"
    "static __inline int __builtin___snprintf_chk(char*s,__mcc_size_t n,int flag,__mcc_size_t slen,const char*fmt,...){\n"
    "__builtin_va_list ap;\n"
    "int r;\n"
    "(void)flag;\n"
    "if(slen!=(__mcc_size_t)-1&&n>slen)\n"
    "__chk_fail();\n"
    "__builtin_va_start(ap,fmt);\n"
    "r=__builtin_vsnprintf(s,n,fmt,ap);\n"
    "__builtin_va_end(ap);\n"
    "return r;\n"
    "}\n"
    "static __inline int __builtin___vsprintf_chk(char*s,int flag,__mcc_size_t slen,const char*fmt,__builtin_va_list ap){\n"
    "(void)flag;\n"
    "if(slen==(__mcc_size_t)-1)\n"
    "return __builtin_vsprintf(s,fmt,ap);\n"
    "{\n"
    "int r=__builtin_vsnprintf(s,slen,fmt,ap);\n"
    "if((__mcc_size_t)r>=slen)\n"
    "__chk_fail();\n"
    "return r;\n"
    "}\n"
    "}\n"
    "static __inline int __builtin___sprintf_chk(char*s,int flag,__mcc_size_t slen,const char*fmt,...){\n"
    "__builtin_va_list ap;\n"
    "int r;\n"
    "(void)flag;\n"
    "__builtin_va_start(ap,fmt);\n"
    "if(slen==(__mcc_size_t)-1){\n"
    "r=__builtin_vsprintf(s,fmt,ap);\n"
    "}else{\n"
    "r=__builtin_vsnprintf(s,slen,fmt,ap);\n"
    "if((__mcc_size_t)r>=slen)\n"
    "__chk_fail();\n"
    "}\n"
    "__builtin_va_end(ap);\n"
    "return r;\n"
    "}\n"

    "#define __MCC_OV_DECL(T,NM) int __mcc_addo_##NM(T,T,T*);int __mcc_subo_##NM(T,T,T*);int __mcc_mulo_##NM(T,T,T*);\n"
    "#define __MCC_OV_DECL_W(T,W,NM) int __mcc_addo_##NM(W,W,T*);int __mcc_subo_##NM(W,W,T*);int __mcc_mulo_##NM(W,W,T*);\n"
    "__MCC_OV_DECL_W(signed char,long long,sc)\n"
    "__MCC_OV_DECL_W(char,long long,c)\n"
    "__MCC_OV_DECL_W(short,long long,s)\n"
    "__MCC_OV_DECL_W(int,long long,i)\n"
    "__MCC_OV_DECL_W(unsigned char,unsigned long long,uc)\n"
    "__MCC_OV_DECL_W(unsigned short,unsigned long long,us)\n"
    "__MCC_OV_DECL_W(unsigned int,unsigned long long,u)\n"
    "#if __SIZEOF_LONG__==8\n"
    "__MCC_OV_DECL(long,l)\n"
    "__MCC_OV_DECL(unsigned long,ul)\n"
    "#else\n"
    "__MCC_OV_DECL_W(long,long long,l)\n"
    "__MCC_OV_DECL_W(unsigned long,unsigned long long,ul)\n"
    "#endif\n"
    "__MCC_OV_DECL(long long,ll)\n"
    "__MCC_OV_DECL(unsigned long long,ull)\n"
    "#ifdef __SIZEOF_INT128__\n"
    "__MCC_OV_DECL(__mcc_int128_t,ti)\n"
    "__MCC_OV_DECL(__mcc_uint128_t,uti)\n"
    "#endif\n"
    "#undef __MCC_OV_DECL\n"
    "#undef __MCC_OV_DECL_W\n"
    "#ifdef __SIZEOF_INT128__\n"
    "#define __mcc_ov_disp_ti(op) __mcc_int128_t:__mcc_##op##o_ti,__mcc_uint128_t:__mcc_##op##o_uti,\n"
    "#else\n"
    "#define __mcc_ov_disp_ti(op)\n"
    "#endif\n"
    "#define __mcc_ov_disp(op,res) _Generic((res),__mcc_ov_disp_ti(op)__mcc_schar_t:__mcc_##op##o_sc,__mcc_char_t:__mcc_##op##o_c,__mcc_short_t:__mcc_##op##o_s,__mcc_int_t:__mcc_##op##o_i,__mcc_long_t:__mcc_##op##o_l,__mcc_llong_t:__mcc_##op##o_ll,__mcc_uchar_t:__mcc_##op##o_uc,__mcc_ushort_t:__mcc_##op##o_us,__mcc_uint_t:__mcc_##op##o_u,__mcc_ulong_t:__mcc_##op##o_ul,__mcc_ullong_t:__mcc_##op##o_ull)\n"
    "#define __builtin_add_overflow(a,b,res) (__mcc_ov_disp(add,*(res))((a),(b),(res)))\n"
    "#define __builtin_sub_overflow(a,b,res) (__mcc_ov_disp(sub,*(res))((a),(b),(res)))\n"
    "#define __builtin_mul_overflow(a,b,res) (__mcc_ov_disp(mul,*(res))((a),(b),(res)))\n"
    "#define __builtin_add_overflow_p(a,b,c) ({__typeof__(c)__mcc_ovp_r;__builtin_add_overflow((a),(b),&__mcc_ovp_r);})\n"
    "#define __builtin_sub_overflow_p(a,b,c) ({__typeof__(c)__mcc_ovp_r;__builtin_sub_overflow((a),(b),&__mcc_ovp_r);})\n"
    "#define __builtin_mul_overflow_p(a,b,c) ({__typeof__(c)__mcc_ovp_r;__builtin_mul_overflow((a),(b),&__mcc_ovp_r);})\n"
    "#define __builtin_assoc_barrier(x) (x)\n"
    "#define __builtin_assume(cond) ((void)0)\n"

    "#endif\n"
