set(SOURCE "winlibs")
set(ENTRIES
    "https://github.com/brechtsanders/winlibs_mingw/releases/download/16.1.0posix-14.0.0-ucrt-r3/winlibs-x86_64-posix-seh-gcc-16.1.0-mingw-w64ucrt-14.0.0-r3.zip|4273565109cd8ab8ecef1b0dc2a56fd7f5c7ee0885840a1c011b9325160ec0c3|/home/llg/Projects/mcc/vendor/winlibs-mingw-w64-16.1.0-ucrt-x86_64"
)

foreach(_entry IN LISTS ENTRIES)
    string(REPLACE "|" ";" _parts "${_entry}")
    list(GET _parts 0 _url)
    list(GET _parts 1 _sha)
    list(GET _parts 2 _dest)
    if(_url STREQUAL "")
        message(FATAL_ERROR
            "mingw-toolchain: no archive URL for source '${SOURCE}'. "
            "For multilib, set -DMCC_MINGW_MULTILIB_URL=<archive-url>.")
    endif()
    if(EXISTS "${_dest}/.mcc-mingw-stamp")
        message(STATUS "mingw-toolchain: ${_dest} already present (delete its "
                       ".mcc-mingw-stamp to refetch)")
        continue()
    endif()
    get_filename_component(_zip "${_dest}.download" ABSOLUTE)
    message(STATUS "mingw-toolchain: downloading ${_url}")
    set(_hashargs "")
    if(NOT _sha STREQUAL "")
        set(_hashargs EXPECTED_HASH SHA256=${_sha})
    endif()
    file(DOWNLOAD "${_url}" "${_zip}" STATUS _st SHOW_PROGRESS TIMEOUT 3600 ${_hashargs})
    list(GET _st 0 _code)
    if(NOT _code EQUAL 0)
        file(REMOVE "${_zip}")
        message(FATAL_ERROR "mingw-toolchain: download failed (${_st}): ${_url}")
    endif()
    file(REMOVE_RECURSE "${_dest}")
    file(MAKE_DIRECTORY "${_dest}")
    message(STATUS "mingw-toolchain: extracting into ${_dest}")
    file(ARCHIVE_EXTRACT INPUT "${_zip}" DESTINATION "${_dest}")
    file(REMOVE "${_zip}")
    file(WRITE "${_dest}/.mcc-mingw-stamp" "${_url}\n")
    message(STATUS "mingw-toolchain: established ${_dest}")
endforeach()
