
cmake_minimum_required(VERSION 3.22)
if(NOT DEFINED TOOL)
    message(FATAL_ERROR "toolchain-setup: pass -DTOOL=gcc|wine|mingw")
endif()

find_program(_BREW brew)
find_program(_APT apt-get)
find_program(_DNF dnf)
find_program(_PACMAN pacman)
find_program(_ZYPPER zypper)

set(_cmd "")
if(_BREW)
    if(TOOL STREQUAL "gcc")
        set(_cmd "${_BREW}" install gcc)
    elseif(TOOL STREQUAL "wine")
        set(_cmd "${_BREW}" install --cask --no-quarantine wine-stable)
    elseif(TOOL STREQUAL "mingw")
        set(_cmd "${_BREW}" install mingw-w64)
    endif()
else()

    set(_sudo "")
    if(NOT "$ENV{USER}" STREQUAL "root")
        find_program(_SUDO sudo)
        if(_SUDO)
            set(_sudo "${_SUDO}")
        endif()
    endif()
    if(_APT)
        if(TOOL STREQUAL "gcc")
            set(_pkgs gcc)
        elseif(TOOL STREQUAL "wine")
            set(_pkgs wine)
        elseif(TOOL STREQUAL "mingw")
            set(_pkgs gcc-mingw-w64 g++-mingw-w64)
        endif()
        set(_cmd ${_sudo} "${_APT}" install -y ${_pkgs})
    elseif(_DNF)
        if(TOOL STREQUAL "gcc")
            set(_pkgs gcc)
        elseif(TOOL STREQUAL "wine")
            set(_pkgs wine)
        elseif(TOOL STREQUAL "mingw")
            set(_pkgs mingw64-gcc)
        endif()
        set(_cmd ${_sudo} "${_DNF}" install -y ${_pkgs})
    elseif(_PACMAN)
        if(TOOL STREQUAL "gcc")
            set(_pkgs gcc)
        elseif(TOOL STREQUAL "wine")
            set(_pkgs wine)
        elseif(TOOL STREQUAL "mingw")
            set(_pkgs mingw-w64-gcc)
        endif()
        set(_cmd ${_sudo} "${_PACMAN}" -S --noconfirm ${_pkgs})
    elseif(_ZYPPER)
        if(TOOL STREQUAL "gcc")
            set(_pkgs gcc)
        elseif(TOOL STREQUAL "wine")
            set(_pkgs wine)
        elseif(TOOL STREQUAL "mingw")
            set(_pkgs mingw64-cross-gcc)
        endif()
        set(_cmd ${_sudo} "${_ZYPPER}" install -y ${_pkgs})
    endif()
endif()

if(NOT _cmd)
    message(FATAL_ERROR
        "toolchain-setup(${TOOL}): no supported package manager found "
        "(looked for brew/apt-get/dnf/pacman/zypper). Install '${TOOL}' manually.")
endif()

string(REPLACE ";" " " _pretty "${_cmd}")
message(STATUS "toolchain-setup(${TOOL}): ${_pretty}")
execute_process(COMMAND ${_cmd} RESULT_VARIABLE _rc)
if(NOT _rc EQUAL 0)
    message(FATAL_ERROR "toolchain-setup(${TOOL}): install failed (rc=${_rc})")
endif()
message(STATUS "toolchain-setup(${TOOL}): done -- re-run cmake to detect it")
