set(URL "https://github.com/llvm/llvm-project/releases/download/llvmorg-22.1.8/LLVM-22.1.8-Linux-X64.tar.xz")
set(SHA "df0e1ecf16caf3489a272a5eea4eec9b0d82878f6477fa309504f918a0006384")
set(DEST "/home/llg/Projects/mcc/vendor/llvm-clang")

if(URL STREQUAL "")
    message(FATAL_ERROR
        "clang-toolchain: no MCC_CLANG_URL for this host. Set -DMCC_CLANG_URL=<llvm-release-archive> "
        "(and -DMCC_CLANG_SUBDIR=<top-dir-in-archive>).")
endif()
if(EXISTS "${DEST}/.mcc-clang-stamp")
    message(STATUS "clang-toolchain: ${DEST} already present (delete its .mcc-clang-stamp to refetch)")
    return()
endif()
get_filename_component(_arc "${DEST}.download" ABSOLUTE)
message(STATUS "clang-toolchain: downloading ${URL}")
set(_hashargs "")
if(NOT SHA STREQUAL "")
    set(_hashargs EXPECTED_HASH SHA256=${SHA})
endif()
file(DOWNLOAD "${URL}" "${_arc}" STATUS _st SHOW_PROGRESS TIMEOUT 7200 ${_hashargs})
list(GET _st 0 _code)
if(NOT _code EQUAL 0)
    file(REMOVE "${_arc}")
    message(FATAL_ERROR "clang-toolchain: download failed (${_st}): ${URL}")
endif()
file(REMOVE_RECURSE "${DEST}")
file(MAKE_DIRECTORY "${DEST}")
message(STATUS "clang-toolchain: extracting into ${DEST} (large archive; this takes a while)")
file(ARCHIVE_EXTRACT INPUT "${_arc}" DESTINATION "${DEST}")
file(REMOVE "${_arc}")
file(WRITE "${DEST}/.mcc-clang-stamp" "${URL}\n")
message(STATUS "clang-toolchain: established ${DEST}")
