set(SRC "/home/llg/Projects/mcc/vendor/musl-src")
set(BLD "/home/llg/Projects/mcc/b/musl-build")
set(SR  "/home/llg/Projects/mcc/vendor/musl-sysroot")
if(SR STREQUAL "")
    message(FATAL_ERROR "musl-sysroot: MCC_MUSL_SYSROOT is empty (system-musl mode); nothing to build.")
endif()
if(NOT EXISTS "${SRC}/configure")
    message(FATAL_ERROR "musl-sysroot: no musl source at ${SRC}. Run the `vendor-musl` target first.")
endif()
if(EXISTS "${SR}/lib/libc.so")
    message(STATUS "musl-sysroot: ${SR} already built (delete it to rebuild)")
    return()
endif()
cmake_host_system_information(RESULT _np QUERY NUMBER_OF_LOGICAL_CORES)
file(MAKE_DIRECTORY "${BLD}")
file(MAKE_DIRECTORY "${SR}")
message(STATUS "musl-sysroot: configuring musl (${SRC}) -> ${SR}")
execute_process(COMMAND "${SRC}/configure" "--prefix=${SR}" "--syslibdir=${SR}/lib"
    WORKING_DIRECTORY "${BLD}" RESULT_VARIABLE _rc)
if(NOT _rc EQUAL 0)
    message(FATAL_ERROR "musl-sysroot: configure failed (${_rc})")
endif()
message(STATUS "musl-sysroot: building (make -j${_np})")
execute_process(COMMAND make -j${_np} WORKING_DIRECTORY "${BLD}" RESULT_VARIABLE _rc)
if(NOT _rc EQUAL 0)
    message(FATAL_ERROR "musl-sysroot: make failed (${_rc})")
endif()
execute_process(COMMAND make install WORKING_DIRECTORY "${BLD}" RESULT_VARIABLE _rc)
if(NOT _rc EQUAL 0)
    message(FATAL_ERROR "musl-sysroot: make install failed (${_rc})")
endif()
message(STATUS "musl-sysroot: established ${SR}")
