set(GIT "/usr/bin/git")
set(URL "https://github.com/ifduyue/musl")
set(MIRROR "https://git.musl-libc.org/git/musl")
set(TARBALL "https://codeload.github.com/ifduyue/musl/tar.gz/refs/tags/@REF@")
set(REF "v1.2.5")
set(DEST "/home/llg/Projects/mcc/vendor/musl-src")
if(GIT STREQUAL "" OR NOT EXISTS "${GIT}")
    message(FATAL_ERROR "vendor-musl: git not found. Install git or pass -DGIT_EXECUTABLE=<path>.")
endif()
if(EXISTS "${DEST}/.git" OR EXISTS "${DEST}/.vendor-musl.stamp")
    message(STATUS "vendor-musl: ${DEST} already present (delete it to re-fetch)")
    return()
endif()
get_filename_component(_parent "${DEST}" DIRECTORY)
file(MAKE_DIRECTORY "${_parent}")
set(_branchargs "")
if(NOT REF STREQUAL "")
    set(_branchargs --branch "${REF}")
endif()

set(ENV{GIT_TERMINAL_PROMPT} "0")
set(ENV{GIT_HTTP_LOW_SPEED_LIMIT} "1000")
set(ENV{GIT_HTTP_LOW_SPEED_TIME} "30")
set(ENV{GCM_INTERACTIVE} "never")

function(_musl_git_clone url resultvar)
    message(STATUS "vendor-musl: cloning ${url} (${REF}) into ${DEST}")
    execute_process(
        COMMAND "${GIT}" -c credential.helper=
                clone --depth 1 ${_branchargs} "${url}" "${DEST}"
        RESULT_VARIABLE _rc)
    set(${resultvar} "${_rc}" PARENT_SCOPE)
endfunction()

_musl_git_clone("${URL}" _rc)
if(NOT _rc EQUAL 0 AND NOT MIRROR STREQUAL "")
    file(REMOVE_RECURSE "${DEST}")
    message(STATUS "vendor-musl: ${URL} unreachable (${_rc}); trying mirror ${MIRROR}")
    _musl_git_clone("${MIRROR}" _rc)
endif()

if(NOT _rc EQUAL 0 AND NOT TARBALL STREQUAL "")
    file(REMOVE_RECURSE "${DEST}")
    string(REPLACE "@REF@" "${REF}" _turl "${TARBALL}")
    message(STATUS "vendor-musl: git clone failed; downloading tarball ${_turl}")
    set(_tgz "${_parent}/musl-src.tar.gz")
    set(_xdir "${_parent}/musl-src.extract")
    file(REMOVE "${_tgz}")
    file(REMOVE_RECURSE "${_xdir}")
    file(DOWNLOAD "${_turl}" "${_tgz}"
        STATUS _dstat TIMEOUT 300 INACTIVITY_TIMEOUT 30 SHOW_PROGRESS)
    list(GET _dstat 0 _drc)
    if(_drc EQUAL 0)
        file(MAKE_DIRECTORY "${_xdir}")
        file(ARCHIVE_EXTRACT INPUT "${_tgz}" DESTINATION "${_xdir}")
        file(GLOB _tops LIST_DIRECTORIES true "${_xdir}/*")
        list(LENGTH _tops _ntop)
        if(_ntop EQUAL 1)
            list(GET _tops 0 _top)
            file(RENAME "${_top}" "${DEST}")
            file(WRITE "${DEST}/.vendor-musl.stamp" "musl ${REF} from ${_turl}\n")
            set(_rc 0)
        else()
            message(STATUS "vendor-musl: unexpected tarball layout (${_ntop} top-level entries)")
        endif()
        file(REMOVE "${_tgz}")
        file(REMOVE_RECURSE "${_xdir}")
    else()
        list(GET _dstat 1 _dmsg)
        message(STATUS "vendor-musl: tarball download failed: ${_dmsg}")
    endif()
endif()

if(NOT _rc EQUAL 0)
    file(REMOVE_RECURSE "${DEST}")
    message(FATAL_ERROR
        "vendor-musl: could not obtain musl ${REF}. Tried:\n"
        "  git   ${URL}\n"
        "  git   ${MIRROR}\n"
        "  https ${TARBALL}\n"
        "Point -DMCC_MUSL_URL / -DMCC_MUSL_MIRROR / -DMCC_MUSL_TARBALL at a reachable "
        "source, or pre-populate ${DEST}.")
endif()
message(STATUS "vendor-musl: established ${DEST}")
