if(NOT MCC OR NOT SRC OR NOT OUT)
    message(FATAL_ERROR "usage: -DMCC= -DSRC= -DOUT= -DEXPECT_RC= [-DREPLAYED=] -P replay.cmake")
endif()

file(MAKE_DIRECTORY "${OUT}")

get_filename_component(_name "${SRC}" NAME_WE)
set(_o0 "${OUT}/${_name}.O0")
set(_r1 "${OUT}/${_name}.R1")

function(build_and_run out_exe expect_rc env_on out_all)
    if(env_on)
        set(_opt "-O1")
        set(_env "${CMAKE_COMMAND}" -E env MCC_AST_REPLAY_DUMP=1)
        if(TEMPLATES)
            list(APPEND _env MCC_AST_TEMPLATES=1)
        else()
            list(APPEND _env MCC_AST_TEMPLATES=0)
        endif()
        if(PROMOTE)
            list(APPEND _env MCC_AST_PROMOTE=1)
        else()
            list(APPEND _env MCC_AST_PROMOTE=0)
        endif()
        if(INLINE)
            list(APPEND _env MCC_AST_INLINE=1)
        else()
            list(APPEND _env MCC_AST_INLINE=0)
        endif()
    else()
        set(_opt "-O0")
        set(_env "${CMAKE_COMMAND}" -E env)
    endif()
    execute_process(
        COMMAND ${_env} "${MCC}" "-B${BDIR}" "${_opt}" "${SRC}" -o "${out_exe}"
        OUTPUT_VARIABLE _co ERROR_VARIABLE _ce RESULT_VARIABLE _crc)
    if(NOT _crc EQUAL 0)
        message(FATAL_ERROR "compile failed (replay=${env_on}) for ${SRC} (rc=${_crc}):\n${_co}${_ce}")
    endif()
    execute_process(COMMAND "${out_exe}" RESULT_VARIABLE _rrc)
    if(NOT _rrc EQUAL expect_rc)
        message(FATAL_ERROR "run (replay=${env_on}) exit ${_rrc}, expected ${expect_rc} for ${SRC}")
    endif()
    set(${out_all} "${_co}${_ce}" PARENT_SCOPE)
endfunction()

build_and_run("${_o0}" "${EXPECT_RC}" OFF _o0_all)
build_and_run("${_r1}" "${EXPECT_RC}" ON _r1_all)

if(REPLAYED)
    if(NOT _r1_all MATCHES "\\[ast-replay\\] ${REPLAYED}\n")
        message(FATAL_ERROR "expected function '${REPLAYED}' to go through the AST replay path, but it fell back:\n${_r1_all}")
    endif()
endif()

if(PROMOTES)
    string(REPLACE "," ";" _promotes "${PROMOTES}")
    foreach(_fn IN LISTS _promotes)
        if(NOT _r1_all MATCHES "\\[ast-promote\\] ([1-9][0-9]*) ${_fn}\n")
            message(FATAL_ERROR "expected register promotion to fire on '${_fn}', but it did not:\n${_r1_all}")
        endif()
    endforeach()
endif()

if(INLINES)
    string(REPLACE "," ";" _inlines "${INLINES}")
    foreach(_fn IN LISTS _inlines)
        if(NOT _r1_all MATCHES "\\[ast-inline\\] grafted ${_fn}\n")
            message(FATAL_ERROR "expected virtual-inline to graft '${_fn}', but it did not:\n${_r1_all}")
        endif()
    endforeach()
endif()

if(SPECIALIZES)
    string(REPLACE "," ";" _specs "${SPECIALIZES}")
    foreach(_fn IN LISTS _specs)
        if(NOT _r1_all MATCHES "\\[ast-inline\\] specialized ${_fn} ")
            message(FATAL_ERROR "expected per-site specialization to fire on '${_fn}', but it did not:\n${_r1_all}")
        endif()
    endforeach()
endif()

if(REEMITS)
    string(REPLACE "," ";" _reemits "${REEMITS}")
    foreach(_fn IN LISTS _reemits)
        if(NOT _r1_all MATCHES "\\[ast-inline\\] re-emitted ${_fn} ")
            message(FATAL_ERROR "expected defer-to-TU to re-emit '${_fn}', but it did not:\n${_r1_all}")
        endif()
    endforeach()
endif()

if(FOLDS)
    if(NOT _r1_all MATCHES "\\[ast-template\\] const-fold ([1-9][0-9]*) ${FOLDS}\n")
        message(FATAL_ERROR "expected the const-fold template to fire on '${FOLDS}', but it did not (fell back or folded nothing):\n${_r1_all}")
    endif()
endif()

if(NOREPLAY)
    if(_r1_all MATCHES "\\[ast-replay\\] ${NOREPLAY}\n")
        message(FATAL_ERROR "expected function '${NOREPLAY}' to fall back, but it replayed:\n${_r1_all}")
    endif()
endif()

message(STATUS "ast/replay ${_name}: -O0 and replay both exit ${EXPECT_RC}")
