cmake_minimum_required(VERSION 3.22)

if(NOT MCC OR NOT CORPUS OR NOT BASELINE OR NOT TMPDIR)
    message(FATAL_ERROR "verify_ratchet: MCC, CORPUS, BASELINE, TMPDIR are required")
endif()

if(NOT OPT)
    set(OPT "-O2")
endif()

if(NOT DEFINED MCCLAUNCH)
    set(MCCLAUNCH "")
endif()
if(NOT DEFINED MCCFLAGS)
    set(MCCFLAGS "")
endif()
if(NOT DEFINED MCCPATHPREFIX)
    set(MCCPATHPREFIX "")
endif()

file(MAKE_DIRECTORY "${TMPDIR}")

file(GLOB_RECURSE _srcs "${CORPUS}/*.c")
if(EXTRA)
    list(APPEND _srcs ${EXTRA})
endif()
list(SORT _srcs)

set(_gaps "")
foreach(_f ${_srcs})
    file(RELATIVE_PATH _rel "${CORPUS}" "${_f}")
    execute_process(
        COMMAND "${CMAKE_COMMAND}" -E env "MCC_AST_VERIFY=1" "MCC_AST_TEMPLATES=0"
                ${MCCLAUNCH} "${MCC}" ${MCCFLAGS} -w "${OPT}" -c
                -o "${MCCPATHPREFIX}${TMPDIR}/verify_sweep.o" "${MCCPATHPREFIX}${_f}"
        OUTPUT_QUIET ERROR_VARIABLE _err RESULT_VARIABLE _rc)
    string(REPLACE "\n" ";" _lines "${_err}")
    foreach(_ln ${_lines})
        if(_ln MATCHES "\\[ast-verify\\] (desync|unfaithful|stackresidue|bail)(:[0-9]+)?\t[^\t]*\t(.+)")
            list(APPEND _gaps "${_rel}\t${CMAKE_MATCH_3}\t${CMAKE_MATCH_1}")
        endif()
    endforeach()
endforeach()
list(SORT _gaps)
list(JOIN _gaps "\n" _current)

if(REGEN)
    file(WRITE "${BASELINE}" "${_current}\n")
    list(LENGTH _gaps _n)
    message(STATUS "verify_ratchet: wrote ${_n} baseline gaps to ${BASELINE}")
    return()
endif()

if(NOT EXISTS "${BASELINE}")
    message(STATUS "verify_ratchet: no baseline for this target (${BASELINE}); SKIP — regenerate with REGEN=1")
    cmake_language(EXIT 77)
endif()

file(READ "${BASELINE}" _base_raw)
string(REPLACE "\r" "" _base_raw "${_base_raw}")
string(STRIP "${_base_raw}" _base_raw)
set(_baseline "")
if(NOT _base_raw STREQUAL "")
    string(REPLACE "\n" ";" _baseline "${_base_raw}")
endif()
list(SORT _baseline)

set(_gap_keys "")
foreach(_g ${_gaps})
    string(REGEX REPLACE "\t[^\t]+$" "" _k "${_g}")
    list(APPEND _gap_keys "${_k}")
endforeach()
set(_base_keys "")
foreach(_b ${_baseline})
    string(REGEX REPLACE "\t[^\t]+$" "" _k "${_b}")
    list(APPEND _base_keys "${_k}")
endforeach()
set(_new_gaps "")
foreach(_g ${_gaps})
    string(REGEX REPLACE "\t[^\t]+$" "" _k "${_g}")
    if(NOT _k IN_LIST _base_keys)
        list(APPEND _new_gaps "${_g}")
    endif()
endforeach()
set(_fixed "")
foreach(_b ${_baseline})
    string(REGEX REPLACE "\t[^\t]+$" "" _k "${_b}")
    if(NOT _k IN_LIST _gap_keys)
        list(APPEND _fixed "${_b}")
    endif()
endforeach()

list(LENGTH _gaps _ng)
list(LENGTH _baseline _nb)
message(STATUS "verify_ratchet: ${_ng} gaps now, ${_nb} in baseline")

if(_new_gaps OR _fixed)
    if(_new_gaps)
        message(STATUS "verify_ratchet: NEW recorder-fidelity gaps (regressions):")
        foreach(_g ${_new_gaps})
            message(STATUS "  + ${_g}")
        endforeach()
    endif()
    if(_fixed)
        message(STATUS "verify_ratchet: baseline gaps now FAITHFUL (regenerate to bank the win):")
        foreach(_g ${_fixed})
            message(STATUS "  - ${_g}")
        endforeach()
    endif()
    message(FATAL_ERROR "verify_ratchet: gap set drifted from baseline (see above)")
endif()

message(STATUS "verify_ratchet: gap set matches baseline — OK")
