cmake_minimum_required(VERSION 3.22)

if(NOT MCC OR NOT CORPUS OR NOT BASELINE OR NOT TMPDIR)
    message(FATAL_ERROR "verify_ratchet: MCC, CORPUS, BASELINE, TMPDIR are required")
endif()

if(NOT OPT)
    set(OPT "-O2")
endif()

if(NOT DEFINED MCCLAUNCH)
    set(MCCLAUNCH "")
endif()
if(NOT DEFINED MCCFLAGS)
    set(MCCFLAGS "")
endif()
if(NOT DEFINED MCCPATHPREFIX)
    set(MCCPATHPREFIX "")
endif()

file(MAKE_DIRECTORY "${TMPDIR}")

file(GLOB_RECURSE _srcs "${CORPUS}/*.c")
if(EXTRA)
    list(APPEND _srcs ${EXTRA})
endif()
list(SORT _srcs)

set(_gaps "")
set(_ast_faithful "")
set(_ast_empty "")
set(_ast_tried 0)
set(_jrn_rows 0)
set(_jrn_faithful 0)
set(_jrn_empty 0)
set(_jrn_vac "")
set(_jrn_bad "")
set(_jrn_clean 0)
set(_jrn_rawops 0)
set(_jrn_rawbytes 0)
set(_jrn_deep 0)
set(_jrn_fix 0)
set(_jrn_ops 0)
set(_jrn_dirty "")
foreach(_f ${_srcs})
    file(RELATIVE_PATH _rel "${CORPUS}" "${_f}")
    execute_process(
        COMMAND "${CMAKE_COMMAND}" -E env "MCC_AST_VERIFY=1" "MCC_AST_TEMPLATES=0"
                "MCC_JOURNAL=1"
                ${MCCLAUNCH} "${MCC}" ${MCCFLAGS} -w "${OPT}" -c
                -o "${MCCPATHPREFIX}${TMPDIR}/verify_sweep.o" "${MCCPATHPREFIX}${_f}"
        OUTPUT_QUIET ERROR_VARIABLE _err RESULT_VARIABLE _rc)
    string(REPLACE "\n" ";" _lines "${_err}")
    foreach(_ln ${_lines})
        if(_ln MATCHES "\\[ast-verify\\] (desync|unfaithful|stackresidue|bail)(:[0-9]+)?\t[^\t]*\t(.+)")
            list(APPEND _gaps "${_rel}\t${CMAKE_MATCH_3}\t${CMAKE_MATCH_1}")
        endif()
        if(_ln MATCHES "\\[ast-verify\\] ([^\t]+)\t[^\t]*\t(.+)")
            set(_v "${CMAKE_MATCH_1}")
            set(_fn "${CMAKE_MATCH_2}")
            if(NOT _v MATCHES "^skip:")
                math(EXPR _ast_tried "${_ast_tried} + 1")
            endif()
            if(_v STREQUAL "faithful")
                list(APPEND _ast_faithful "${_rel}\t${_fn}")
            elseif(_v STREQUAL "empty")
                list(APPEND _ast_empty "${_rel}\t${_fn}")
            endif()
        endif()
        if(_ln MATCHES "\\[jrn-verify\\] ([^\t]+)\t[^\t]*\t([^\t]+)\tops=")
            set(_v "${CMAKE_MATCH_1}")
            math(EXPR _jrn_rows "${_jrn_rows} + 1")
            if(_v STREQUAL "jfaithful")
                math(EXPR _jrn_faithful "${_jrn_faithful} + 1")
            elseif(_v STREQUAL "jempty")
                math(EXPR _jrn_empty "${_jrn_empty} + 1")
                list(APPEND _jrn_vac "${_rel}\t${CMAKE_MATCH_2}")
            else()
                list(APPEND _jrn_bad "${_rel}\t${CMAKE_MATCH_2}\t${_v}")
            endif()
        endif()
        if(_ln MATCHES "\\[jrn-verify\\] ([^\t]+)\t[^\t]*\t([^\t]+)\tops=([0-9]+)\traw=([0-9]+)\tfix=([0-9]+)\trawb=([0-9]+)\tdeep=([0-9]+)")
            set(_v "${CMAKE_MATCH_1}")
            math(EXPR _jrn_rawops   "${_jrn_rawops}   + ${CMAKE_MATCH_4}")
            math(EXPR _jrn_rawbytes "${_jrn_rawbytes} + ${CMAKE_MATCH_6}")
            math(EXPR _jrn_deep     "${_jrn_deep}     + ${CMAKE_MATCH_7}")
            math(EXPR _jrn_fix      "${_jrn_fix}      + ${CMAKE_MATCH_5}")
            math(EXPR _jrn_ops      "${_jrn_ops}      + ${CMAKE_MATCH_3}")
            if(CMAKE_MATCH_4 GREATER 0)
                list(APPEND _jrn_dirty "${_rel}\t${CMAKE_MATCH_2}\traw=${CMAKE_MATCH_4}\trawb=${CMAKE_MATCH_6}")
            elseif(_v STREQUAL "jfaithful")
                math(EXPR _jrn_clean "${_jrn_clean} + 1")
            endif()
        endif()
    endforeach()
endforeach()
list(SORT _gaps)
list(JOIN _gaps "\n" _current)

list(LENGTH _ast_faithful _n_ast_faithful)

set(_both_vacuous 0)
foreach(_e ${_ast_empty})
    if(_e IN_LIST _jrn_vac)
        math(EXPR _both_vacuous "${_both_vacuous} + 1")
    endif()
endforeach()
math(EXPR _jrn_ok "${_jrn_faithful} + ${_jrn_empty}")
math(EXPR _tree_ok "${_n_ast_faithful} + ${_both_vacuous}")
math(EXPR _delta "${_jrn_ok} - ${_tree_ok}")
set(_parity_violations "")
foreach(_b ${_jrn_bad})
    string(REGEX REPLACE "\t[^\t]+$" "" _k "${_b}")
    if(_k IN_LIST _ast_faithful)
        list(APPEND _parity_violations "${_b}")
    endif()
endforeach()

if(_jrn_rows GREATER 0)
    message(STATUS "verify_ratchet: parity ${OPT} — tree faithful ${_n_ast_faithful}, "
                   "journal faithful ${_jrn_ok} (${_jrn_faithful} + ${_jrn_empty} vacuous) "
                   "of ${_jrn_rows} journalled, delta ${_delta} "
                   "(${_both_vacuous} vacuous on both sides, not counted)")
endif()

if(JOURNAL)
    if(_jrn_rows EQUAL 0)
        message(STATUS "verify_ratchet: no [jrn-verify] rows — this build has no "
                       "MCC_JOURNAL_HOOKS; journal column SKIP")
        cmake_language(EXIT 77)
    endif()
    if(NOT _jrn_rows EQUAL _ast_tried)
        message(FATAL_ERROR "verify_ratchet: journal observed ${_jrn_rows} functions but the "
                            "recorder attempted ${_ast_tried} — the journal hooks are not firing "
                            "on every body")
    endif()
    if(_parity_violations)
        message(STATUS "verify_ratchet: journal REGRESSED on functions the tree reproduces:")
        foreach(_v ${_parity_violations})
            message(STATUS "  ! ${_v}")
        endforeach()
        list(LENGTH _parity_violations _nv)
        message(FATAL_ERROR "verify_ratchet: ${_nv} parity violation(s) — the journal must be "
                            "faithful wherever the tree is")
    endif()
    list(LENGTH _jrn_bad _n_jrn_bad)
    message(STATUS "verify_ratchet: journal parity OK — ${_n_jrn_bad} non-faithful journal "
                   "verdict(s), none on ground the tree holds")
    list(LENGTH _jrn_dirty _n_jrn_dirty)
    message(STATUS "verify_ratchet: journal honesty ${OPT} — clean ${_jrn_clean} of "
                   "${_jrn_rows} journalled, ${_n_jrn_dirty} function(s) with raw blobs, "
                   "${_jrn_rawops} raw op(s) / ${_jrn_rawbytes} B certified by memcpy")
    message(STATUS "verify_ratchet: journal depth ${OPT} — ${_jrn_fix} fixup(s) over "
                   "${_jrn_ops} op(s), ${_jrn_deep} op(s) with a register live below the top two")
    if(NOT JBASELINE)
        return()
    endif()
    if(JDEPTHFILE)
        set(_jdepth "${JDEPTHFILE}")
    else()
        string(REGEX REPLACE "\\.txt$" ".depth.txt" _jdepth "${JBASELINE}")
    endif()
    if(JREGEN AND JDEPTHREGEN)
        file(WRITE "${_jdepth}"
             "fix=${_jrn_fix}\ndeep=${_jrn_deep}\nrows=${_jrn_rows}\nops=${_jrn_ops}\n")
        message(STATUS "verify_ratchet: wrote depth ceiling fix=${_jrn_fix} deep=${_jrn_deep} "
                       "over ${_jrn_rows} journalled row(s) / ${_jrn_ops} op(s) to ${_jdepth}")
    elseif(JREGEN)
        message(STATUS "verify_ratchet: depth ceiling NOT banked — this run may bank "
                       "breadth but not depth, which is native-sensitive. Re-run with "
                       "MODE=native to bank ${_jdepth}")
    elseif(EXISTS "${_jdepth}")
        file(READ "${_jdepth}" _jd_raw)
        string(REPLACE "\r" "" _jd_raw "${_jd_raw}")
        set(_jd_fix "")
        set(_jd_deep "")
        set(_jd_rows "")
        set(_jd_ops "")
        if(_jd_raw MATCHES "fix=([0-9]+)")
            set(_jd_fix "${CMAKE_MATCH_1}")
        endif()
        if(_jd_raw MATCHES "deep=([0-9]+)")
            set(_jd_deep "${CMAKE_MATCH_1}")
        endif()
        if(_jd_raw MATCHES "rows=([0-9]+)")
            set(_jd_rows "${CMAKE_MATCH_1}")
        endif()
        if(_jd_raw MATCHES "ops=([0-9]+)")
            set(_jd_ops "${CMAKE_MATCH_1}")
        endif()
        if(_jd_fix STREQUAL "" OR _jd_deep STREQUAL "")
            message(FATAL_ERROR "verify_ratchet: malformed depth ceiling ${_jdepth} — regenerate with JREGEN=1")
        endif()
        if(NOT _jd_rows STREQUAL "" AND NOT _jd_rows EQUAL _jrn_rows)
            message(STATUS "verify_ratchet: journal depth ceiling NOT COMPARABLE — ${_jdepth} was "
                           "banked over ${_jd_rows} journalled row(s) / ${_jd_ops} op(s), this run "
                           "measured ${_jrn_rows} row(s) / ${_jrn_ops} op(s). That is a different "
                           "corpus (different system headers), not a different model: fix "
                           "${_jd_fix} vs ${_jrn_fix}, deep ${_jd_deep} vs ${_jrn_deep} are not "
                           "counts of the same thing, so the depth check is SKIPPED rather than "
                           "reported as a regression. Rebank in THIS environment with JREGEN=1 to "
                           "restore the ratchet.")
        elseif(_jrn_fix GREATER _jd_fix OR _jrn_deep GREATER _jd_deep)
            message(FATAL_ERROR "verify_ratchet: journal model depth REGRESSED — fix ${_jd_fix} -> "
                                "${_jrn_fix}, deep ${_jd_deep} -> ${_jrn_deep}. Replay is deriving "
                                "less of the vstack than it did; if this is intended, rebank with JREGEN=1")
        elseif(_jrn_fix LESS _jd_fix OR _jrn_deep LESS _jd_deep)
            message(STATUS "verify_ratchet: journal model depth IMPROVED — fix ${_jd_fix} -> "
                           "${_jrn_fix}, deep ${_jd_deep} -> ${_jrn_deep} (regenerate to tighten the ceiling)")
        else()
            message(STATUS "verify_ratchet: journal model depth matches ceiling — OK")
        endif()
    else()
        set(_depth_unbanked 1)
    endif()
    list(SORT _jrn_dirty)
    list(JOIN _jrn_dirty "\n" _jrn_current)
    if(JREGEN)
        file(WRITE "${JBASELINE}" "#rows=${_jrn_rows}\n${_jrn_current}\n")
        message(STATUS "verify_ratchet: wrote ${_n_jrn_dirty} journal-honesty rows to ${JBASELINE} "
                       "over ${_jrn_rows} journalled row(s)")
        return()
    endif()
    if(NOT EXISTS "${JBASELINE}")
        message(STATUS "verify_ratchet: no journal-honesty baseline for this target (${JBASELINE}); SKIP — regenerate with JREGEN=1")
        cmake_language(EXIT 77)
    endif()
    file(READ "${JBASELINE}" _jbase_raw)
    string(REPLACE "\r" "" _jbase_raw "${_jbase_raw}")
    string(STRIP "${_jbase_raw}" _jbase_raw)
    set(_jbaseline "")
    set(_jb_rows "")
    if(NOT _jbase_raw STREQUAL "")
        string(REPLACE "\n" ";" _jbase_lines "${_jbase_raw}")
        foreach(_l ${_jbase_lines})
            if(_l MATCHES "^#rows=([0-9]+)$")
                set(_jb_rows "${CMAKE_MATCH_1}")
            else()
                list(APPEND _jbaseline "${_l}")
            endif()
        endforeach()
    endif()
    list(SORT _jbaseline)
    set(_new_dirty "")
    foreach(_d ${_jrn_dirty})
        if(NOT _d IN_LIST _jbaseline)
            list(APPEND _new_dirty "${_d}")
        endif()
    endforeach()
    set(_banked "")
    foreach(_b ${_jbaseline})
        if(NOT _b IN_LIST _jrn_dirty)
            list(APPEND _banked "${_b}")
        endif()
    endforeach()
    if(_new_dirty OR _banked)
        if(NOT _jb_rows STREQUAL "" AND NOT _jb_rows EQUAL _jrn_rows)
            message(STATUS "verify_ratchet: journal honesty NOT COMPARABLE — ${JBASELINE} was "
                           "banked over ${_jb_rows} journalled row(s), this run measured "
                           "${_jrn_rows}. That is a different corpus (different system headers), "
                           "not a different model: a function present on one side and absent on "
                           "the other is a corpus difference, not a verdict, so the honesty check "
                           "is SKIPPED rather than reported as a regression or as a win. Rebank in "
                           "THIS environment with JREGEN=1 to restore the ratchet.")
            foreach(_d ${_new_dirty})
                message(STATUS "  ? only in this run: ${_d}")
            endforeach()
            foreach(_d ${_banked})
                message(STATUS "  ? only in the baseline: ${_d}")
            endforeach()
            return()
        endif()
        if(_new_dirty)
            message(STATUS "verify_ratchet: NEW journal raw blobs (regressions):")
            foreach(_d ${_new_dirty})
                message(STATUS "  + ${_d}")
            endforeach()
        endif()
        if(_banked)
            message(STATUS "verify_ratchet: baseline raw blobs now CLEAN (regenerate to bank the win):")
            foreach(_d ${_banked})
                message(STATUS "  - ${_d}")
            endforeach()
        endif()
        message(FATAL_ERROR "verify_ratchet: journal honesty drifted from baseline (see above)")
    endif()
    message(STATUS "verify_ratchet: journal honesty matches baseline — OK")
    if(_depth_unbanked)
        message(STATUS "verify_ratchet: breadth checked, depth NOT checked — no "
                       "ceiling at ${_jdepth}. Depth may only be banked from a "
                       "MODE=native run, so this key is half-ratcheted and reports "
                       "SKIP rather than a pass. A breadth regression still fails.")
        cmake_language(EXIT 77)
    endif()
    return()
endif()

if(REGEN)
    file(WRITE "${BASELINE}" "${_current}\n")
    list(LENGTH _gaps _n)
    message(STATUS "verify_ratchet: wrote ${_n} baseline gaps to ${BASELINE}")
    return()
endif()

if(NOT EXISTS "${BASELINE}")
    message(STATUS "verify_ratchet: no baseline for this target (${BASELINE}); SKIP — regenerate with REGEN=1")
    cmake_language(EXIT 77)
endif()

file(READ "${BASELINE}" _base_raw)
string(REPLACE "\r" "" _base_raw "${_base_raw}")
string(STRIP "${_base_raw}" _base_raw)
set(_baseline "")
if(NOT _base_raw STREQUAL "")
    string(REPLACE "\n" ";" _baseline "${_base_raw}")
endif()
list(SORT _baseline)

set(_gap_keys "")
foreach(_g ${_gaps})
    string(REGEX REPLACE "\t[^\t]+$" "" _k "${_g}")
    list(APPEND _gap_keys "${_k}")
endforeach()
set(_base_keys "")
foreach(_b ${_baseline})
    string(REGEX REPLACE "\t[^\t]+$" "" _k "${_b}")
    list(APPEND _base_keys "${_k}")
endforeach()
set(_new_gaps "")
foreach(_g ${_gaps})
    string(REGEX REPLACE "\t[^\t]+$" "" _k "${_g}")
    if(NOT _k IN_LIST _base_keys)
        list(APPEND _new_gaps "${_g}")
    endif()
endforeach()
set(_fixed "")
foreach(_b ${_baseline})
    string(REGEX REPLACE "\t[^\t]+$" "" _k "${_b}")
    if(NOT _k IN_LIST _gap_keys)
        list(APPEND _fixed "${_b}")
    endif()
endforeach()

list(LENGTH _gaps _ng)
list(LENGTH _baseline _nb)
message(STATUS "verify_ratchet: ${_ng} gaps now, ${_nb} in baseline")

if(_new_gaps OR _fixed)
    if(_new_gaps)
        message(STATUS "verify_ratchet: NEW recorder-fidelity gaps (regressions):")
        foreach(_g ${_new_gaps})
            message(STATUS "  + ${_g}")
        endforeach()
    endif()
    if(_fixed)
        message(STATUS "verify_ratchet: baseline gaps now FAITHFUL (regenerate to bank the win):")
        foreach(_g ${_fixed})
            message(STATUS "  - ${_g}")
        endforeach()
    endif()
    message(FATAL_ERROR "verify_ratchet: gap set drifted from baseline (see above)")
endif()

message(STATUS "verify_ratchet: gap set matches baseline — OK")
