#!/usr/bin/env python3
# Generator for tests/fold/int64_float.c (T-mac-30082).
# Bakes correctly single-rounded int64/uint64 -> IEEE binary32 values (round
# half to even) so the test can assert the compiler's const-fold matches both
# the runtime SCVTF/UCVTF conversion and the true single-rounded result.
# Run: python3 tests/fold/gen_i2f.py tests/fold/int64_float.c
import sys

def single_round_i2f32(n):
    if n == 0:
        return 0
    sign = 0
    if n < 0:
        sign = 0x80000000
        n = -n
    bl = n.bit_length()
    if bl <= 24:
        m = n; e = 0
    else:
        sh = bl - 24
        low = n & ((1 << sh) - 1)
        m = n >> sh
        half = 1 << (sh - 1)
        if low > half or (low == half and (m & 1)):
            m += 1
            if m == (1 << 24):
                m >>= 1; sh += 1
        e = sh
    biased = e + 23 + 127
    if biased >= 255:
        return sign | 0x7f800000
    return sign | (biased << 23) | (m & 0x7fffff)

# Values with >53 significant bits landing near a float rounding boundary
# (where double-rounding via a 53-bit long double diverges from a single
# correctly-rounded conversion), signed and unsigned.
signed = [18014399583223809, -18014399583223809,
          9223372036854775807, 1311768467463790320, -1311768467463790320]
unsigned = [18014399583223809, 18446744073709551615,
            9223372036854775809, 0xFEDCBA9876543210]

L = []
L.append('/* Regression for T-mac-30082: int64->float CONSTANT conversion must be')
L.append(' * single correctly-rounded (ISO C 6.3.1.4), matching runtime SCVTF/UCVTF —')
L.append(' * not double-rounded via host long double. For each value the const-folded')
L.append(' * float is compared against the runtime conversion of the same value')
L.append(' * (through a volatile) and the baked correctly-rounded bits. Generated by')
L.append(' * tests/fold/gen_i2f.py. main returns the fail count (0 == pass).')
L.append(' * -DMCC_I2F_MUTATE flips one expected value to prove the harness bites. */')
L.append('#include <stdio.h>')
L.append('#include <string.h>')
L.append('static int fails = 0, checks = 0;')
L.append('static unsigned fbits(float f){ unsigned u; memcpy(&u, &f, 4); return u; }')
L.append('#ifdef MCC_I2F_MUTATE')
L.append('#define WANT(w) ((w) ^ 1u)')
L.append('#else')
L.append('#define WANT(w) (w)')
L.append('#endif')
L.append('#define CKI(CONST, RTTYPE, WANT_BITS, TAG) do { checks++; \\')
L.append('    volatile RTTYPE _v = (RTTYPE)(CONST); \\')
L.append('    float _rt = (float)_v; \\')
L.append('    float _cf = (float)(CONST); \\')
L.append('    unsigned _w = WANT(WANT_BITS##u); \\')
L.append('    if (fbits(_cf) != _w) { fails++; \\')
L.append('        printf("FAIL %s fold=0x%08x want=0x%08x\\n", TAG, fbits(_cf), _w); } \\')
L.append('    if (fbits(_cf) != fbits(_rt)) { fails++; \\')
L.append('        printf("FAIL %s fold=0x%08x runtime=0x%08x\\n", TAG, fbits(_cf), fbits(_rt)); } \\')
L.append('} while (0)')
L.append('int main(void) {')
for v in signed:
    L.append(f'  CKI({v}LL, long long, 0x{single_round_i2f32(v):08x}, "s{v}");')
for v in unsigned:
    L.append(f'  CKI({v}ULL, unsigned long long, 0x{single_round_i2f32(v):08x}, "u{v}");')
L.append('  printf("i2f checks=%d fails=%d\\n", checks, fails);')
L.append('  return fails;')
L.append('}')

out = sys.argv[1] if len(sys.argv) > 1 else 'tests/fold/int64_float.c'
open(out, 'w').write('\n'.join(L) + '\n')
print("wrote", out, "-", len(signed) + len(unsigned), "values x2 checks")
