/* Regression for T-mac-30082: int64->float CONSTANT conversion must be
 * single correctly-rounded (ISO C 6.3.1.4), matching runtime SCVTF/UCVTF —
 * not double-rounded via host long double. For each value the const-folded
 * float is compared against the runtime conversion of the same value
 * (through a volatile) and the baked correctly-rounded bits. Generated by
 * tests/fold/gen_i2f.py. main returns the fail count (0 == pass).
 * -DMCC_I2F_MUTATE flips one expected value to prove the harness bites. */
#include <stdio.h>
#include <string.h>
static int fails = 0, checks = 0;
static unsigned fbits(float f){ unsigned u; memcpy(&u, &f, 4); return u; }
#ifdef MCC_I2F_MUTATE
#define WANT(w) ((w) ^ 1u)
#else
#define WANT(w) (w)
#endif
#define CKI(CONST, RTTYPE, WANT_BITS, TAG) do { checks++; \
    volatile RTTYPE _v = (RTTYPE)(CONST); \
    float _rt = (float)_v; \
    float _cf = (float)(CONST); \
    unsigned _w = WANT(WANT_BITS##u); \
    if (fbits(_cf) != _w) { fails++; \
        printf("FAIL %s fold=0x%08x want=0x%08x\n", TAG, fbits(_cf), _w); } \
    if (fbits(_cf) != fbits(_rt)) { fails++; \
        printf("FAIL %s fold=0x%08x runtime=0x%08x\n", TAG, fbits(_cf), fbits(_rt)); } \
} while (0)
int main(void) {
  CKI(18014399583223809LL, long long, 0x5a800001, "s18014399583223809");
  CKI(-18014399583223809LL, long long, 0xda800001, "s-18014399583223809");
  CKI(9223372036854775807LL, long long, 0x5f000000, "s9223372036854775807");
  CKI(1311768467463790320LL, long long, 0x5d91a2b4, "s1311768467463790320");
  CKI(-1311768467463790320LL, long long, 0xdd91a2b4, "s-1311768467463790320");
  CKI(18014399583223809ULL, unsigned long long, 0x5a800001, "u18014399583223809");
  CKI(18446744073709551615ULL, unsigned long long, 0x5f800000, "u18446744073709551615");
  CKI(9223372036854775809ULL, unsigned long long, 0x5f000000, "u9223372036854775809");
  CKI(18364758544493064720ULL, unsigned long long, 0x5f7edcbb, "u18364758544493064720");
  printf("i2f checks=%d fails=%d\n", checks, fails);
  return fails;
}
