#include <stdio.h>
#include <string.h>

const char *platform_macros[] = {
    "__i386__",             "TCC_TARGET_I386",
    "__x86_64__",           "TCC_TARGET_X86_64",
    "_WIN32",               "TCC_TARGET_PE",
    "__arm__",              "TCC_TARGET_ARM",
    "__ARM_EABI__",         "TCC_ARM_EABI",
    "__aarch64__",          "TCC_TARGET_ARM64",
    "__riscv",              "TCC_TARGET_RISCV64",
    "__APPLE__",            "TCC_TARGET_MACHO",
    "__FreeBSD__",          "TARGETOS_FreeBSD",
    "__FreeBSD_kernel__",   "TARGETOS_FreeBSD_kernel",
    "__OpenBSD__",          "TARGETOS_OpenBSD",
    "__NetBSD__",           "TARGETOS_NetBSD",
    "__linux__",            "TARGETOS_Linux",
    "__ANDROID__",          "TARGETOS_ANDROID",

    "__SIZEOF_POINTER__",   "PTR_SIZE",
    "__SIZEOF_LONG__",      "LONG_SIZE",
    0
};

int isid(int c)
{
    return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z')
        || (c >= '0' && c <= '9') || c == '_';
}

int isspc(int c)
{
    return (unsigned char)c <= ' ' && c != 0;
}

int main(int argc, char **argv)
{
    char l[1000], l2[1000], *p, *q, *p0;
    FILE *fp, *op;
    int c, e, f, s, cmt, cmt_n;
    const char *r;

    if (argc < 3)
        return 1;

    fp = fopen(argv[1], "rb");
    op = fopen(argv[2], "wb");
    if (!fp || !op) {
        fprintf(stderr, "c2str: file error\n");
        return 1;
    }

    cmt = cmt_n = 0;
    for (;;) {
        p = l;
    append:
        if (fgets(p, sizeof l - (p - l), fp)) {
            p = strchr(p, 0);
            while (p > l && isspc(p[-1]))
                --p;
            *p = 0;
        } else if (p == l)
            break;

        if (p > l && p[-1] == '\\') {
            p[-1] = ' ';
            goto append;
        }

        p = l, q = l2, f = 0;
        while (*p && isspc(*p))
            ++p, ++f;

        if (p[0] == '/' && cmt == 0) {
            if (p[1] == '*')
                cmt = 2;
            if (p[1] == '/')
                cmt = 1;
        }
        if (cmt) {
            fprintf(op, "%s", l);
            if (++cmt_n == 1)
                fprintf(op, " (converted, do not edit this file)");
            fprintf(op, "\n");
            if (cmt == 1)
                cmt = 0;
            if (cmt == 2) {
                p = strchr(l, 0);
                if (p >= l + 2 && p[-1] == '/' && p[-2] == '*')
                    cmt = 0;
            }
            continue;
        }

        if (f < 4) {
            do {
                for (e = f = 0; (r = platform_macros[f]); f += 2) {
                    c = strlen(r);
                    if (0 == memcmp(p + e, r, c)) {
                        p += e + c;
                        q = strchr(strcpy(q, platform_macros[f + 1]), 0);
                        break;
                    }

                }
                if (r)
                    continue;
            } while (!!(*q++ = *p++));
            fprintf(op, "%s\n", l2);
            continue;

        } else {
            s = e = f = 0, p0 = p;
            for (;;) {
                c = *p++;

                if (isspc(c)) {
                    s = 1;
                    continue;
                }
                if (c == '/' && (p[0] == '/' || p[0] == '*'))
                    c = 0;
                else if (s && q > l2
                    && ((isid(q[-1]) && isid(c))
                        || (q >= l2 + 2
                            && l2[0] == '#'
                            && l2[1] == 'd'
                            && f < 2 && !e
                            )))
                    *q++ = ' ', ++f;
                s = 0;

                if (c == '(')
                    ++e;
                if (c == ')')
                    --e;
                if (c == '\\' || c == '\"')
                    *q++ = '\\';
                *q++ = c;
                if (c == 0)
                    break;
                p0 = p;
            }
            fprintf(op, "    \"%s\\n\"%s\n", l2, p0);
        }
    }

    fclose(fp);
    fclose(op);
    return 0;
}
