#ifndef MCC_CI_ARTIFACTS_H
#define MCC_CI_ARTIFACTS_H

static const char TMPL_CI_YML[] =
		"name: CI\n"
		"\n"
		"on:\n"
		"  push:\n"
		"  pull_request:\n"
		"  workflow_dispatch:\n"
		"\n"
		"concurrency:\n"
		"  group: ci-${{ github.ref }}\n"
		"  # Cancel superseded runs on PRs and on main: a newer push to the same ref\n"
		"  # supersedes the in-progress run, so consecutive commits stop queueing behind\n"
		"  # (and starving the shared runner pools of) each other. Tag pushes are\n"
		"  # excluded so a release-tag run always completes.\n"
		"  cancel-in-progress: ${{ github.event_name == 'pull_request' || github.ref == 'refs/heads/main' }}\n"
		"\n"
		"permissions:\n"
		"  contents: read\n"
		"\n"
		"jobs:\n"
		"  plan:\n"
		"    # Every job matrix below is generated from the preset ledger in\n"
		"    # tools/ci.c (`ci plan --job <x>`), so the schedule has exactly one\n"
		"    # source of truth, shared with `ci local` and checked by `ci parity`.\n"
		"    runs-on: ubuntu-latest\n"
		"    outputs:\n"
		"      linux: ${{ steps.gen.outputs.linux }}\n"
		"      macos: ${{ steps.gen.outputs.macos }}\n"
		"      windows: ${{ steps.gen.outputs.windows }}\n"
		"      qemu: ${{ steps.gen.outputs.qemu }}\n"
		"    steps:\n"
		"      - uses: actions/checkout@v5\n"
		"      - id: gen\n"
		"        run: |\n"
		"          @BOOT@\n"
		"          echo \"linux=$(/tmp/mcc-ci plan --job linux)\" >> \"$GITHUB_OUTPUT\"\n"
		"          echo \"macos=$(/tmp/mcc-ci plan --job macos)\" >> \"$GITHUB_OUTPUT\"\n"
		"          echo \"windows=$(/tmp/mcc-ci plan --job windows)\" >> \"$GITHUB_OUTPUT\"\n"
		"          echo \"qemu=$(/tmp/mcc-ci plan --job qemu)\" >> \"$GITHUB_OUTPUT\"\n"
		"\n"
		"  linux:\n"
		"    needs: plan\n"
		"    name: ${{ matrix.preset }} / ${{ matrix.arch }}\n"
		"    runs-on: ${{ matrix.arch == 'arm64' && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}\n"
		"    strategy:\n"
		"      fail-fast: false\n"
		"      matrix:\n"
		"        include: ${{ fromJSON(needs.plan.outputs.linux) }}\n"
		"    env:\n"
		"      ART: mcc-${{ matrix.preset }}-${{ matrix.arch }}\n"
		"    steps:\n"
		"      - uses: actions/checkout@v5\n"
		"      - name: install toolchain (everything the platform offers)\n"
		"        run: |\n"
		"          sudo apt-get update\n"
		"          sudo apt-get install -y --no-install-recommends \\\n"
		"            cmake ninja-build build-essential gcc clang lld wine64 git rsync \\\n"
		"            mingw-w64\n"
		"      - name: run ${{ matrix.preset }}\n"
		"        run: |\n"
		"          @BOOT@\n"
		"          mkdir -p \"dist/$ART\"\n"
		"          /tmp/mcc-ci run-preset ${{ matrix.preset }} --out \"dist/$ART\" ${{ matrix.flags }}\n"
		"      - name: test summary\n"
		"        if: always()\n"
		"        run: |\n"
		"          /tmp/mcc-ci junit-summary \"cmake-${{ matrix.preset }}/ctest-junit.xml\" \\\n"
		"            \"${{ matrix.preset }} / ${{ matrix.arch }}\" >> \"$GITHUB_STEP_SUMMARY\" || true\n"
		"      - name: pack build targets\n"
		"        run: tar cJf \"$ART.tar.xz\" -C dist \"$ART\"\n"
		"      - uses: actions/upload-artifact@v7\n"
		"        with:\n"
		"          name: ${{ env.ART }}\n"
		"          path: ${{ env.ART }}.tar.xz\n"
		"\n"
		"  macos:\n"
		"    # Native arm64 cells only. The emulated x86_64 macOS cells (build + test\n"
		"    # under Rosetta, ~14 min each) were the gating critical path, so they were\n"
		"    # split out to the push-to-main Matrix workflow (`ci plan --job macos-x86`),\n"
		"    # same as bench and the superbuild.\n"
		"    needs: plan\n"
		"    name: ${{ matrix.preset }} / ${{ matrix.cc }} / ${{ matrix.arch }}\n"
		"    runs-on: macos-15\n"
		"    strategy:\n"
		"      fail-fast: false\n"
		"      matrix:\n"
		"        include: ${{ fromJSON(needs.plan.outputs.macos) }}\n"
		"    env:\n"
		"      ART: mcc-${{ matrix.preset }}-${{ matrix.cc }}-${{ matrix.arch }}\n"
		"    steps:\n"
		"      - uses: actions/checkout@v5\n"
		"      - name: install Rosetta 2 (x86_64 cells + x86_64 wine on Apple silicon)\n"
		"        run: sudo softwareupdate --install-rosetta --agree-to-license\n"
		"      - name: cache Homebrew downloads (gcc bottle + deps)\n"
		"        uses: actions/cache@v5\n"
		"        with:\n"
		"          path: ~/Library/Caches/Homebrew/downloads\n"
		"          key: brew-${{ runner.os }}-${{ runner.arch }}-cmake-ninja-gcc-mingw\n"
		"      - name: install toolchain (everything the platform offers)\n"
		"        run: |\n"
		"          brew untap aws/tap 2>/dev/null || true\n"
		"          brew install cmake ninja gcc\n"
		"      - name: install mingw-w64 (PE reference compiler; conformance/diff3 oracle)\n"
		"        continue-on-error: true\n"
		"        run: brew install mingw-w64\n"
		"      - name: install wine (drives pe-wine-conformance in macos-cross)\n"
		"        continue-on-error: true\n"
		"        run: HOMEBREW_CASK_OPTS=--no-quarantine brew install --cask wine-stable\n"
		"      - name: resolve compiler (CC for the preset)\n"
		"        run: |\n"
		"          if [ \"${{ matrix.cc }}\" = gcc ]; then\n"
		"            g=$(ls \"$(brew --prefix)\"/bin/gcc-[0-9]* | sort -V | tail -1)\n"
		"            echo \"CC=$g\" >> \"$GITHUB_ENV\"\n"
		"          else\n"
		"            echo \"CC=clang\" >> \"$GITHUB_ENV\"\n"
		"          fi\n"
		"      - name: run ${{ matrix.preset }} (configure + build + test + install)\n"
		"        # The benchmark lives in its own workflow (bench.yml, push-to-main\n"
		"        # only) so per-push/PR CI is not gated on a ~10-min compile-speed run.\n"
		"        run: |\n"
		"          cc -O2 -o /tmp/mcc-ci tools/ci.c tools/toolsupport.c\n"
		"          extra=\"\"\n"
		"          if [ \"${{ matrix.arch }}\" = x86_64 ]; then\n"
		"            extra=\"-DCMAKE_OSX_ARCHITECTURES=x86_64 -DMCC_TARGET_ARCH=x86_64\"\n"
		"            # The x86_64 cell runs under Rosetta; also drop the arch-independent\n"
		"            # object-format cli probes (symbol typing / response file / fat64),\n"
		"            # which serialize on the Rosetta translation lock for ~70s here yet\n"
		"            # are fully covered by the native arm64 macOS and Linux cells.\n"
		"            export MCC_CI_CTEST_EXCLUDE='^(fuzz|ast|cst|diff3|preprocess)/|^cli/(symbol_type_func_object|response_file|macho_fat64_dylib)$'\n"
		"          fi\n"
		"          /tmp/mcc-ci run-preset ${{ matrix.preset }} --out \"$PWD/dist/$ART\" \\\n"
		"            \"-DMCC_DIST_PLAT=$ART\" $extra\n"
		"      - name: pack build targets\n"
		"        run: tar cJf \"$ART.tar.xz\" -C dist \"$ART\"\n"
		"      - uses: actions/upload-artifact@v7\n"
		"        with:\n"
		"          name: ${{ env.ART }}\n"
		"          path: ${{ env.ART }}.tar.xz\n"
		"\n"
		"  windows:\n"
		"    # msvc and mingw are both Windows toolchains, so they share one job: the\n"
		"    # matrix (`ci plan --job windows`) carries msvc cells (cl, VS generator,\n"
		"    # native x86_64 + arm64) alongside mingw cells (winlibs GCC superbuild,\n"
		"    # Ninja, x86_64 + i686), distinguished by matrix.mingw. Every cell runs\n"
		"    # the full ctest suite and diffs mcc against whatever reference compilers\n"
		"    # (gcc/clang) the image offers, so side-by-side coverage is maximal. The\n"
		"    # 32-bit mingw cell is experimental (matrix.experimental), so it reports\n"
		"    # but does not gate until i386-Windows codegen is proven green.\n"
		"    needs: plan\n"
		"    name: ${{ matrix.preset }} / ${{ matrix.arch }}\n"
		"    runs-on: ${{ matrix.runner }}\n"
		"    continue-on-error: ${{ matrix.experimental || false }}\n"
		"    strategy:\n"
		"      fail-fast: false\n"
		"      matrix:\n"
		"        include: ${{ fromJSON(needs.plan.outputs.windows) }}\n"
		"    env:\n"
		"      ART: mcc-${{ matrix.preset }}-${{ matrix.arch }}\n"
		"    steps:\n"
		"      - uses: actions/checkout@v5\n"
		"      - name: set up MSVC dev shell (cl bootstraps the ci tool + mingw driver)\n"
		"        uses: TheMrMilchmann/setup-msvc-dev@v4\n"
		"        with:\n"
		"          arch: ${{ matrix.msvcarch }}\n"
		"      - name: install ninja (mingw superbuild uses the Ninja generator)\n"
		"        if: matrix.mingw\n"
		"        run: choco install ninja -y\n"
		"      - name: cache winlibs mingw toolchain (superbuild download target)\n"
		"        if: matrix.mingw\n"
		"        uses: actions/cache@v5\n"
		"        with:\n"
		"          path: vendor/winlibs-mingw-w64-*\n"
		"          key: winlibs-${{ hashFiles('CMakeLists.txt') }}\n"
		"          restore-keys: winlibs-\n"
		"      - name: resolve diff3 reference compilers (prefer preinstalled mingw gcc + clang)\n"
		"        continue-on-error: true\n"
		"        shell: pwsh\n"
		"        run: |\n"
		"          $gcc   = (Get-Command gcc   -ErrorAction SilentlyContinue).Source\n"
		"          $clang = (Get-Command clang -ErrorAction SilentlyContinue).Source\n"
		"          if ($gcc)   { \"MCC_DIFF3_GCC=$($gcc.Replace('\\','/'))\"     | Out-File -FilePath $env:GITHUB_ENV -Append }\n"
		"          if ($clang) { \"MCC_DIFF3_CLANG=$($clang.Replace('\\','/'))\" | Out-File -FilePath $env:GITHUB_ENV -Append }\n"
		"          if ($gcc -and $clang) { \"MCC_DIFF3_READY=1\" | Out-File -FilePath $env:GITHUB_ENV -Append }\n"
		"      - name: install diff3 reference compilers (only if the image lacks gcc or clang)\n"
		"        if: env.MCC_DIFF3_READY != '1'\n"
		"        continue-on-error: true\n"
		"        run: choco install -y llvm mingw\n"
		"      - name: re-resolve diff3 reference compilers after install\n"
		"        if: env.MCC_DIFF3_READY != '1'\n"
		"        continue-on-error: true\n"
		"        shell: pwsh\n"
		"        run: |\n"
		"          $gcc   = (Get-Command gcc   -ErrorAction SilentlyContinue).Source\n"
		"          $clang = (Get-Command clang -ErrorAction SilentlyContinue).Source\n"
		"          if ($gcc)   { \"MCC_DIFF3_GCC=$($gcc.Replace('\\','/'))\"     | Out-File -FilePath $env:GITHUB_ENV -Append }\n"
		"          if ($clang) { \"MCC_DIFF3_CLANG=$($clang.Replace('\\','/'))\" | Out-File -FilePath $env:GITHUB_ENV -Append }\n"
		"      - name: run ${{ matrix.preset }} (msvc - configure + build + test + install)\n"
		"        if: ${{ !matrix.mingw }}\n"
		"        # --timeout caps any single test: a hung test (e.g. a thread-contention\n"
		"        # deadlock that only manifests on real arm64 silicon) is killed and named\n"
		"        # in the log instead of stalling the whole job until it is cancelled.\n"
		"        # Benchmark runs in bench.yml (push-to-main only), not here.\n"
		"        run: |\n"
		"          cl /nologo /O2 /Fe:ci.exe tools\\ci.c tools\\toolsupport.c\n"
		"          .\\ci.exe run-preset ${{ matrix.preset }} --config Release --out \"$($PWD.Path.Replace('\\','/'))/dist/${env:ART}\" \"-DMCC_DIST_PLAT=${env:ART}\" -- --timeout 300\n"
		"      - name: run ${{ matrix.preset }} (mingw superbuild - fetches winlibs GCC; each cell builds + ctest)\n"
		"        if: matrix.mingw\n"
		"        # --no-test suppresses only the empty top-level ctest; the winlibs cell\n"
		"        # runs the full suite (and emits ctest-junit.xml) inside the superbuild.\n"
		"        run: |\n"
		"          cl /nologo /O2 /Fe:ci.exe tools\\ci.c tools\\toolsupport.c\n"
		"          .\\ci.exe run-preset mingw --no-test --out \"$($PWD.Path.Replace('\\','/'))/dist/${env:ART}\" \"-DMCC_DIST_PLAT=${env:ART}\" \"-DMCC_MINGW_ARCH=${{ matrix.arch }}\"\n"
		"      - name: test summary\n"
		"        if: always()\n"
		"        shell: pwsh\n"
		"        run: |\n"
		"          if (-not (Test-Path ci.exe)) { exit 0 }\n"
		"          $xml = if (\"${{ matrix.mingw }}\" -eq \"true\") { \"cmake-mingw/mingw-native/ctest-junit.xml\" } else { \"cmake-${{ matrix.preset }}/ctest-junit.xml\" }\n"
		"          .\\ci.exe junit-summary \"$xml\" \"${{ matrix.preset }} / ${{ matrix.arch }}\" | Out-File -FilePath \"${env:GITHUB_STEP_SUMMARY}\" -Append -Encoding utf8\n"
		"      - name: pack build targets\n"
		"        run: tar cJf \"${env:ART}.tar.xz\" -C dist \"${env:ART}\"\n"
		"      - uses: actions/upload-artifact@v7\n"
		"        with:\n"
		"          name: ${{ env.ART }}\n"
		"          path: ${{ env.ART }}.tar.xz\n"
		"\n"
		"  qemu:\n"
		"    # user-mode qemu exists only on Linux, so this runs natively on the ubuntu\n"
		"    # runners (no Docker), on both host arches. One job per (host x batch),\n"
		"    # where a batch runs its arches x {glibc,musl} in a single umbrella `qemu`\n"
		"    # build: the emulated work per cell is tiny, so batching amortizes the\n"
		"    # apt/checkout/cache setup that used to dominate 20 one-cell jobs. The\n"
		"    # stage3 sysroots are target-side data, keyed by batch and shared across\n"
		"    # hosts via the restore-key prefix.\n"
		"    needs: plan\n"
		"    name: qemu / ${{ matrix.host }} / ${{ matrix.label }}\n"
		"    runs-on: ${{ matrix.host == 'arm64' && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}\n"
		"    strategy:\n"
		"      fail-fast: false\n"
		"      matrix:\n"
		"        include: ${{ fromJSON(needs.plan.outputs.qemu) }}\n"
		"    steps:\n"
		"      - uses: actions/checkout@v5\n"
		"      - name: install qemu-user + toolchain\n"
		"        run: |\n"
		"          sudo apt-get update\n"
		"          sudo apt-get install -y --no-install-recommends \\\n"
		"            build-essential cmake ninja-build make git ca-certificates curl \\\n"
		"            qemu-user qemu-user-static tar xz-utils bzip2 rsync clang lld\n"
		"      - name: cache stage3 sysroot\n"
		"        uses: actions/cache@v5\n"
		"        with:\n"
		"          path: vendor/gentoo-stage3-*\n"
		"          key: gentoo-stage3-${{ matrix.batch }}\n"
		"          restore-keys: gentoo-stage3-\n"
		"      - name: run qemu batch ${{ matrix.batch }} (${{ matrix.label }})\n"
		"        env:\n"
		"          ARCHS: ${{ matrix.archs }}\n"
		"          LIBCS: glibc;musl\n"
		"        run: |\n"
		"          @BOOT@\n"
		"          /tmp/mcc-ci qemu\n"
		"      - name: test summary\n"
		"        if: always()\n"
		"        run: |\n"
		"          /tmp/mcc-ci junit-summary \"cmake-qemu/ctest-junit.xml\" \\\n"
		"            \"qemu / ${{ matrix.host }} / ${{ matrix.label }}\" >> \"$GITHUB_STEP_SUMMARY\" || true\n"
		"";

static const char TMPL_DIST_YML[] =
		"name: Dist\n"
		"\n"
		"# Dist pipeline: runs nightly (packaging smoke, version ci-<sha12>), is\n"
		"# callable by release.yml (tagged bundles, version = the tag), and on demand.\n"
		"# It was on every per-push/PR run via ci.yml, but packaging verification does\n"
		"# not gate and its Windows cells were the slowest jobs, so it moved to a\n"
		"# nightly cadence with bench/matrix. The cell matrices come from the preset\n"
		"# ledger via `ci plan --job dist-unix` / `--job dist-windows`, and every flow\n"
		"# step is a `ci` tool verb.\n"
		"\n"
		"on:\n"
		"  schedule:\n"
		"    - cron: '15 5 * * *'\n"
		"  workflow_dispatch:\n"
		"  workflow_call:\n"
		"    inputs:\n"
		"      version:\n"
		"        description: Bundle version tag (empty = ci-<sha12>)\n"
		"        type: string\n"
		"        default: ''\n"
		"        required: false\n"
		"      bench:\n"
		"        description: Run the compile-speed benchmark as part of dist (releases do; per-push smoke does not)\n"
		"        type: boolean\n"
		"        default: false\n"
		"        required: false\n"
		"\n"
		"permissions:\n"
		"  contents: read\n"
		"\n"
		"jobs:\n"
		"  plan:\n"
		"    runs-on: ubuntu-latest\n"
		"    outputs:\n"
		"      unix: ${{ steps.gen.outputs.unix }}\n"
		"      windows: ${{ steps.gen.outputs.windows }}\n"
		"    steps:\n"
		"      - uses: actions/checkout@v5\n"
		"      - id: gen\n"
		"        run: |\n"
		"          @BOOT@\n"
		"          echo \"unix=$(/tmp/mcc-ci plan --job dist-unix)\" >> \"$GITHUB_OUTPUT\"\n"
		"          echo \"windows=$(/tmp/mcc-ci plan --job dist-windows)\" >> \"$GITHUB_OUTPUT\"\n"
		"\n"
		"  unix:\n"
		"    needs: plan\n"
		"    name: ${{ matrix.plat }}\n"
		"    runs-on: ${{ matrix.os }}\n"
		"    strategy:\n"
		"      fail-fast: false\n"
		"      matrix:\n"
		"        include: ${{ fromJSON(needs.plan.outputs.unix) }}\n"
		"    env:\n"
		"      VERSION: ${{ inputs.version }}\n"
		"    steps:\n"
		"      - uses: actions/checkout@v5\n"
		"      - name: install toolchain (linux)\n"
		"        if: runner.os == 'Linux'\n"
		"        run: |\n"
		"          sudo apt-get update\n"
		"          sudo apt-get install -y --no-install-recommends cmake ninja-build gcc clang\n"
		"      - name: install Rosetta 2 (run x86_64 binaries on Apple silicon)\n"
		"        if: matrix.rosetta\n"
		"        run: sudo softwareupdate --install-rosetta --agree-to-license\n"
		"      - name: install toolchain (macos)\n"
		"        if: runner.os == 'macOS'\n"
		"        run: |\n"
		"          brew untap aws/tap 2>/dev/null || true\n"
		"          brew install cmake ninja\n"
		"      - name: dist (configure + build + install + strip + package; bench on release)\n"
		"        # `ci dist` runs the whole flow (the macOS local-symbol strip is\n"
		"        # folded in); Rosetta's cross flags pass through after `--`. The\n"
		"        # compile-speed bench is skipped (--no-bench) unless inputs.bench.\n"
		"        run: |\n"
		"          set -eux\n"
		"          cc -O2 -o /tmp/mcc-ci tools/ci.c tools/toolsupport.c $([ \"$RUNNER_OS\" = Linux ] && echo -ldl)\n"
		"          extra=\"\"\n"
		"          if [ \"${{ matrix.rosetta }}\" = \"true\" ]; then\n"
		"            extra=\"-- -DCMAKE_OSX_ARCHITECTURES=x86_64 -DMCC_TARGET_ARCH=x86_64\"\n"
		"          fi\n"
		"          /tmp/mcc-ci dist --preset ${{ matrix.preset }} --plat ${{ matrix.plat }} \\\n"
		"            --version \"${VERSION:-ci-${GITHUB_SHA::12}}\" \\\n"
		"            $([ \"${{ inputs.bench }}\" = true ] || echo --no-bench) $extra\n"
		"      - name: benchmark summary\n"
		"        if: ${{ inputs.bench }}\n"
		"        run: /tmp/mcc-ci bench-summary --plat \"${{ matrix.plat }}\" --append \"$GITHUB_STEP_SUMMARY\"\n"
		"      - uses: actions/upload-artifact@v7\n"
		"        with:\n"
		"          name: mcc-${{ matrix.plat }}\n"
		"          path: |\n"
		"            dist/*.tar.xz\n"
		"            dist/checksums-*.txt\n"
		"            dist/bench-*.txt\n"
		"\n"
		"  windows:\n"
		"    needs: plan\n"
		"    name: ${{ matrix.plat }}\n"
		"    runs-on: ${{ matrix.runner }}\n"
		"    strategy:\n"
		"      fail-fast: false\n"
		"      matrix:\n"
		"        include: ${{ fromJSON(needs.plan.outputs.windows) }}\n"
		"    env:\n"
		"      VERSION: ${{ inputs.version }}\n"
		"    steps:\n"
		"      - uses: actions/checkout@v5\n"
		"      - name: set up MSVC dev shell (cl for the ci bootstrap + mingw driver)\n"
		"        uses: TheMrMilchmann/setup-msvc-dev@v4\n"
		"        with:\n"
		"          arch: ${{ matrix.msvcarch }}\n"
		"      - name: install ninja\n"
		"        if: matrix.mingw\n"
		"        run: choco install ninja -y\n"
		"      - name: cache winlibs mingw toolchain (superbuild download target)\n"
		"        if: matrix.mingw\n"
		"        uses: actions/cache@v5\n"
		"        with:\n"
		"          path: vendor/winlibs-mingw-w64-*\n"
		"          key: winlibs-${{ hashFiles('CMakeLists.txt') }}\n"
		"          restore-keys: winlibs-\n"
		"      - name: dist (configure + build + install + package)\n"
		"        run: |\n"
		"          cl /nologo /O2 /Fe:ci.exe tools\\ci.c tools\\toolsupport.c\n"
		"          if (-not $env:VERSION) { $env:VERSION = \"ci-\" + $env:GITHUB_SHA.Substring(0,12) }\n"
		"          $bench = if (\"${{ inputs.bench }}\" -eq \"true\") { @() } else { ,\"--no-bench\" }\n"
		"          .\\ci.exe dist --preset ${{ matrix.preset }} --plat ${{ matrix.plat }} --version \"$env:VERSION\" @bench\n"
		"      - name: benchmark summary\n"
		"        if: ${{ inputs.bench }}\n"
		"        run: .\\ci.exe bench-summary --plat \"${{ matrix.plat }}\" --append \"${env:GITHUB_STEP_SUMMARY}\"\n"
		"      - uses: actions/upload-artifact@v7\n"
		"        with:\n"
		"          name: mcc-${{ matrix.plat }}\n"
		"          path: |\n"
		"            dist/*.zip\n"
		"            dist/checksums-*.txt\n"
		"            dist/bench-*.txt\n"
		"";

static const char TMPL_RELEASE_YML[] =
		"name: Release\n"
		"\n"
		"on:\n"
		"  push:\n"
		"    tags: ['v*']\n"
		"  workflow_dispatch: {}\n"
		"\n"
		"permissions:\n"
		"  contents: write\n"
		"\n"
		"concurrency:\n"
		"  group: release-${{ github.ref }}\n"
		"  cancel-in-progress: false\n"
		"\n"
		"jobs:\n"
		"\n"
		"  dist:\n"
		"    # Shared dist pipeline (.github/workflows/dist.yml, same one ci.yml runs\n"
		"    # per push), stamped with the tag instead of ci-<sha12>.\n"
		"    uses: ./.github/workflows/dist.yml\n"
		"    permissions:\n"
		"      contents: read\n"
		"    with:\n"
		"      version: ${{ github.ref_name }}\n"
		"      bench: true\n"
		"\n"
		"  publish:\n"
		"    name: publish release\n"
		"    needs: [dist]\n"
		"    if: startsWith(github.ref, 'refs/tags/v')\n"
		"    runs-on: ubuntu-latest\n"
		"    steps:\n"
		"      - uses: actions/checkout@v5\n"
		"      - uses: actions/download-artifact@v7\n"
		"        with:\n"
		"          path: dl\n"
		"      - name: collect + combine checksums\n"
		"        run: |\n"
		"          set -eux\n"
		"          @BOOT@\n"
		"          mkdir -p out\n"
		"          find dl -type f ! -name 'checksums-*.txt' -exec cp {} out/ \\;\n"
		"          /tmp/mcc-ci sha256sums dl --out out/SHA256SUMS.txt\n"
		"          ls -l out\n"
		"      - name: publish GitHub Release\n"
		"        uses: softprops/action-gh-release@v3\n"
		"        with:\n"
		"          files: out/*\n"
		"          generate_release_notes: true\n"
		"          fail_on_unmatched_files: true\n"
		"";

static const char TMPL_BENCH_YML[] =
		"name: Bench\n"
		"\n"
		"# Compile-speed benchmark (self-hosted mcc per -O level vs gcc/clang/mingw/msvc\n"
		"# via mccbench). Split out of the per-push/PR CI matrix — where it was ~50% of\n"
		"# every macOS/MSVC/mingw job's wall-clock and gated the critical path — into its\n"
		"# own push-to-main trigger. It rebuilds mcc (no tests; ci.yml already tests) and\n"
		"# runs the `bench` target on one representative native cell per OS family, so\n"
		"# the reference compilers (gcc+clang+mingw on Linux, msvc on Windows) are all\n"
		"# covered without re-running the whole build matrix. Runs nightly (it was\n"
		"# per-push-to-main, but as a non-gating check it competed with the gating CI\n"
		"# matrix for the shared runner-concurrency cap). Also runnable on demand.\n"
		"\n"
		"on:\n"
		"  schedule:\n"
		"    - cron: '31 4 * * *'\n"
		"  workflow_dispatch:\n"
		"\n"
		"permissions:\n"
		"  contents: read\n"
		"\n"
		"concurrency:\n"
		"  group: bench-${{ github.ref }}\n"
		"  cancel-in-progress: true\n"
		"\n"
		"jobs:\n"
		"  linux:\n"
		"    name: bench / linux-x86_64\n"
		"    runs-on: ubuntu-latest\n"
		"    steps:\n"
		"      - uses: actions/checkout@v5\n"
		"      - name: install toolchain (gcc + clang + mingw references)\n"
		"        run: |\n"
		"          sudo apt-get update\n"
		"          sudo apt-get install -y --no-install-recommends \\\n"
		"            cmake ninja-build build-essential gcc clang lld mingw-w64\n"
		"      - name: build + benchmark (linux-gcc)\n"
		"        run: |\n"
		"          @BOOT@\n"
		"          /tmp/mcc-ci run-preset linux-gcc --no-test --bench \\\n"
		"            -DMCC_BENCH=ON -DMCC_DIST_PLAT=linux-x86_64\n"
		"      - name: benchmark summary\n"
		"        if: always()\n"
		"        run: /tmp/mcc-ci bench-summary --plat linux-x86_64 --append \"$GITHUB_STEP_SUMMARY\"\n"
		"      - uses: actions/upload-artifact@v7\n"
		"        with:\n"
		"          name: bench-linux-x86_64\n"
		"          path: dist/bench-*.txt\n"
		"          if-no-files-found: ignore\n"
		"\n"
		"  macos:\n"
		"    name: bench / macos-arm64\n"
		"    runs-on: macos-15\n"
		"    steps:\n"
		"      - uses: actions/checkout@v5\n"
		"      - name: cache Homebrew downloads (gcc bottle + deps)\n"
		"        uses: actions/cache@v5\n"
		"        with:\n"
		"          path: ~/Library/Caches/Homebrew/downloads\n"
		"          key: brew-${{ runner.os }}-${{ runner.arch }}-cmake-ninja-gcc\n"
		"      - name: install toolchain (clang + gcc references)\n"
		"        run: |\n"
		"          brew untap aws/tap 2>/dev/null || true\n"
		"          brew install cmake ninja gcc\n"
		"      - name: build + benchmark (macos, native arm64)\n"
		"        # The `macos` preset takes its build compiler from $env{CC} (ci.yml\n"
		"        # resolves it per matrix cell); bench builds mcc with the native clang.\n"
		"        env:\n"
		"          CC: clang\n"
		"        run: |\n"
		"          cc -O2 -o /tmp/mcc-ci tools/ci.c tools/toolsupport.c\n"
		"          /tmp/mcc-ci run-preset macos --no-test --bench \\\n"
		"            -DMCC_BENCH=ON -DMCC_DIST_PLAT=macos-arm64\n"
		"      - name: benchmark summary\n"
		"        if: always()\n"
		"        run: /tmp/mcc-ci bench-summary --plat macos-arm64 --append \"$GITHUB_STEP_SUMMARY\"\n"
		"      - uses: actions/upload-artifact@v7\n"
		"        with:\n"
		"          name: bench-macos-arm64\n"
		"          path: dist/bench-*.txt\n"
		"          if-no-files-found: ignore\n"
		"\n"
		"  windows:\n"
		"    name: bench / windows-x86_64-msvc\n"
		"    runs-on: windows-latest\n"
		"    steps:\n"
		"      - uses: actions/checkout@v5\n"
		"      - name: set up MSVC dev shell (cl reference + ci bootstrap)\n"
		"        uses: TheMrMilchmann/setup-msvc-dev@v4\n"
		"        with:\n"
		"          arch: x64\n"
		"      - name: build + benchmark (msvc)\n"
		"        run: |\n"
		"          cl /nologo /O2 /Fe:ci.exe tools\\ci.c tools\\toolsupport.c\n"
		"          .\\ci.exe run-preset msvc --config Release --no-test --bench \"-DMCC_BENCH=ON\" \"-DMCC_DIST_PLAT=windows-x86_64-msvc\"\n"
		"      - name: benchmark summary\n"
		"        if: always()\n"
		"        run: .\\ci.exe bench-summary --plat windows-x86_64-msvc --append \"${env:GITHUB_STEP_SUMMARY}\"\n"
		"      - uses: actions/upload-artifact@v7\n"
		"        with:\n"
		"          name: bench-windows-x86_64-msvc\n"
		"          path: dist/bench-*.txt\n"
		"          if-no-files-found: ignore\n"
		"";

static const char TMPL_MATRIX_YML[] =
		"name: Matrix\n"
		"\n"
		"# Heavy, non-gating cells split out of the per-push/PR CI critical path onto a\n"
		"# nightly trigger (they used to run per-push-to-main, but as non-gating checks\n"
		"# they competed with the gating CI matrix for the shared concurrency cap). Two\n"
		"# families:\n"
		"#\n"
		"#   matrix    - the toolchain superbuild: gcc;clang x native;cross x host-arch,\n"
		"#               one build per cell (each overrides MCC_TOOLCHAIN_PROFILE /\n"
		"#               MCC_TARGETS to a single profile x target) so the 2x2x2 = 8\n"
		"#               builds run in parallel and each surfaces as its own job\n"
		"#               instead of two ~40-min host superbuilds. Build-only smoke\n"
		"#               (ci.yml already tests each toolchain).\n"
		"#   macos-x86 - the emulated x86_64 macOS cells (build + test under Rosetta,\n"
		"#               ~14 min each). These were the gating critical path; ci.yml now\n"
		"#               gates only the native arm64 macOS cells.\n"
		"#\n"
		"# Both come from the same preset ledger as ci.yml (`ci plan --job matrix` /\n"
		"# `--job macos-x86`), so `ci parity` still covers their presets. Never blocks a\n"
		"# PR; also runnable on demand.\n"
		"\n"
		"on:\n"
		"  schedule:\n"
		"    - cron: '47 4 * * *'\n"
		"  workflow_dispatch:\n"
		"\n"
		"permissions:\n"
		"  contents: read\n"
		"\n"
		"concurrency:\n"
		"  group: matrix-${{ github.ref }}\n"
		"  cancel-in-progress: true\n"
		"\n"
		"jobs:\n"
		"  plan:\n"
		"    runs-on: ubuntu-latest\n"
		"    outputs:\n"
		"      matrix: ${{ steps.gen.outputs.matrix }}\n"
		"      macos: ${{ steps.gen.outputs.macos }}\n"
		"    steps:\n"
		"      - uses: actions/checkout@v5\n"
		"      - id: gen\n"
		"        run: |\n"
		"          @BOOT@\n"
		"          echo \"matrix=$(/tmp/mcc-ci plan --job matrix)\" >> \"$GITHUB_OUTPUT\"\n"
		"          echo \"macos=$(/tmp/mcc-ci plan --job macos-x86)\" >> \"$GITHUB_OUTPUT\"\n"
		"\n"
		"  matrix:\n"
		"    needs: plan\n"
		"    name: ${{ matrix.profile }} / ${{ matrix.target }} / ${{ matrix.arch }}\n"
		"    runs-on: ${{ matrix.arch == 'arm64' && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}\n"
		"    strategy:\n"
		"      fail-fast: false\n"
		"      matrix:\n"
		"        include: ${{ fromJSON(needs.plan.outputs.matrix) }}\n"
		"    env:\n"
		"      ART: mcc-${{ matrix.preset }}-${{ matrix.profile }}-${{ matrix.target }}-${{ matrix.arch }}\n"
		"    steps:\n"
		"      - uses: actions/checkout@v5\n"
		"      - name: install toolchain (everything the platform offers)\n"
		"        run: |\n"
		"          sudo apt-get update\n"
		"          sudo apt-get install -y --no-install-recommends \\\n"
		"            cmake ninja-build build-essential gcc clang lld wine64 git rsync \\\n"
		"            mingw-w64\n"
		"      - name: run ${{ matrix.profile }} x ${{ matrix.target }} (single-cell build, build-only)\n"
		"        run: |\n"
		"          @BOOT@\n"
		"          mkdir -p \"dist/$ART\"\n"
		"          /tmp/mcc-ci run-preset ${{ matrix.preset }} --out \"dist/$ART\" --no-test \\\n"
		"            -DMCC_TOOLCHAIN_PROFILE=${{ matrix.profile }} -DMCC_TARGETS=${{ matrix.target }}\n"
		"      - name: pack build targets\n"
		"        run: tar cJf \"$ART.tar.xz\" -C dist \"$ART\"\n"
		"      - uses: actions/upload-artifact@v7\n"
		"        with:\n"
		"          name: ${{ env.ART }}\n"
		"          path: ${{ env.ART }}.tar.xz\n"
		"\n"
		"  macos-x86:\n"
		"    # The emulated x86_64 macOS cells (clang, native + cross), formerly gating\n"
		"    # in ci.yml. Full configure + build + test under Rosetta, so they carry the\n"
		"    # same coverage as the arm64 cells — just off the per-push critical path.\n"
		"    needs: plan\n"
		"    name: ${{ matrix.preset }} / ${{ matrix.cc }} / ${{ matrix.arch }}\n"
		"    runs-on: macos-15\n"
		"    strategy:\n"
		"      fail-fast: false\n"
		"      matrix:\n"
		"        include: ${{ fromJSON(needs.plan.outputs.macos) }}\n"
		"    env:\n"
		"      ART: mcc-${{ matrix.preset }}-${{ matrix.cc }}-${{ matrix.arch }}\n"
		"      # The macos preset resolves its build compiler from $CC; the x86_64\n"
		"      # cells are clang-only, so pin it (the gating arm64 job resolves CC in a\n"
		"      # step because it also runs gcc cells).\n"
		"      CC: clang\n"
		"    steps:\n"
		"      - uses: actions/checkout@v5\n"
		"      - name: install Rosetta 2 (x86_64 build + tests under emulation)\n"
		"        run: sudo softwareupdate --install-rosetta --agree-to-license\n"
		"      - name: cache Homebrew downloads (gcc bottle + deps)\n"
		"        uses: actions/cache@v5\n"
		"        with:\n"
		"          path: ~/Library/Caches/Homebrew/downloads\n"
		"          key: brew-${{ runner.os }}-${{ runner.arch }}-cmake-ninja-gcc-mingw\n"
		"      - name: install toolchain (everything the platform offers)\n"
		"        run: |\n"
		"          brew untap aws/tap 2>/dev/null || true\n"
		"          brew install cmake ninja gcc\n"
		"      - name: install mingw-w64 (PE reference compiler; conformance/diff3 oracle)\n"
		"        continue-on-error: true\n"
		"        run: brew install mingw-w64\n"
		"      - name: install wine (drives pe-wine-conformance in macos-cross)\n"
		"        continue-on-error: true\n"
		"        run: HOMEBREW_CASK_OPTS=--no-quarantine brew install --cask wine-stable\n"
		"      - name: run ${{ matrix.preset }} x86_64 under Rosetta (configure + build + test)\n"
		"        # x86_64 cells are clang-only; the Rosetta translation lock serializes a\n"
		"        # handful of arch-independent probes, so drop those (fully covered by the\n"
		"        # native arm64 macOS and Linux cells).\n"
		"        run: |\n"
		"          cc -O2 -o /tmp/mcc-ci tools/ci.c tools/toolsupport.c\n"
		"          export MCC_CI_CTEST_EXCLUDE='^(fuzz|ast|cst|diff3|preprocess)/|^cli/(symbol_type_func_object|response_file|macho_fat64_dylib)$'\n"
		"          /tmp/mcc-ci run-preset ${{ matrix.preset }} --out \"$PWD/dist/$ART\" \\\n"
		"            \"-DMCC_DIST_PLAT=$ART\" -DCMAKE_OSX_ARCHITECTURES=x86_64 -DMCC_TARGET_ARCH=x86_64\n"
		"";

static const char TMPL_FUZZ_YML[] =
		"name: fuzz-nightly\n"
		"\n"
		"# Scheduled differential-fuzz campaign (TODO §0). Runs the whole-pipeline\n"
		"# miscompile fuzzer for a time budget against gcc+clang as the same-ISA oracle,\n"
		"# with the \"no-new-class in K batches\" stop rule and crash-class dedup in\n"
		"# `fuzz_runner campaign`. x86_64-Linux only (the oracle needs native gcc AND\n"
		"# clang executing mcc's own target ISA). Also runnable on demand.\n"
		"\n"
		"on:\n"
		"  schedule:\n"
		"    - cron: '17 4 * * *'\n"
		"  workflow_dispatch:\n"
		"    inputs:\n"
		"      budget:\n"
		"        description: wall-clock budget in seconds\n"
		"        default: '5400'\n"
		"      batch:\n"
		"        description: seeds per round\n"
		"        default: '50'\n"
		"\n"
		"permissions:\n"
		"  contents: read\n"
		"\n"
		"concurrency:\n"
		"  group: fuzz-nightly\n"
		"  cancel-in-progress: false\n"
		"\n"
		"jobs:\n"
		"  campaign:\n"
		"    runs-on: ubuntu-latest\n"
		"    steps:\n"
		"      - uses: actions/checkout@v5\n"
		"      - name: install toolchain\n"
		"        run: |\n"
		"          sudo apt-get update\n"
		"          sudo apt-get install -y --no-install-recommends \\\n"
		"            cmake ninja-build build-essential gcc clang git\n"
		"      - name: build mcc + fuzz runner\n"
		"        run: |\n"
		"          cmake --preset debug \\\n"
		"            -DMCC_DIFF3_GCC=\"$(command -v gcc)\" \\\n"
		"            -DMCC_DIFF3_CLANG=\"$(command -v clang)\"\n"
		"          cmake --build cmake-debug -j\"$(nproc)\" --target mcc fuzz_runner\n"
		"      - name: run campaign\n"
		"        env:\n"
		"          MCC_FUZZ_SEED: ${{ github.run_number }}0000\n"
		"        run: |\n"
		"          budget='${{ github.event.inputs.budget }}'; budget=\"${budget:-5400}\"\n"
		"          batch='${{ github.event.inputs.batch }}';   batch=\"${batch:-50}\"\n"
		"          set +e\n"
		"          cmake-debug/fuzz_runner campaign \\\n"
		"            cmake-debug/mcc cmake-debug runtime/include \\\n"
		"            tests/fuzz/corpus \"$RUNNER_TEMP/fuzz-work\" \\\n"
		"            \"$budget\" \"$batch\" 20 \\\n"
		"            --ref gcc \"$(command -v gcc)\" --ref clang \"$(command -v clang)\" \\\n"
		"            | tee \"$RUNNER_TEMP/campaign.log\"\n"
		"          echo \"campaign_rc=${PIPESTATUS[0]}\" >> \"$GITHUB_ENV\"\n"
		"      - name: summary\n"
		"        if: always()\n"
		"        run: |\n"
		"          {\n"
		"            echo \"### fuzz-nightly campaign\"\n"
		"            echo '```'\n"
		"            tail -n 20 \"$RUNNER_TEMP/campaign.log\" 2>/dev/null || echo \"(no log)\"\n"
		"            echo '```'\n"
		"          } >> \"$GITHUB_STEP_SUMMARY\"\n"
		"      - name: upload new repros\n"
		"        if: always()\n"
		"        uses: actions/upload-artifact@v7\n"
		"        with:\n"
		"          name: fuzz-repros-${{ github.run_number }}\n"
		"          path: tests/fuzz/corpus/repro_*.c\n"
		"          if-no-files-found: ignore\n"
		"      - name: fail on new miscompile class\n"
		"        if: always()\n"
		"        run: test \"${campaign_rc:-0}\" = \"0\"\n"
		"";

static const char TMPL_CI_DOCKERFILE[] =
		"FROM ubuntu:24.04\n"
		"\n"
		"RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \\\n"
		"        ca-certificates gpg wget \\\n"
		"    && wget -qO- https://apt.kitware.com/keys/kitware-archive-latest.asc \\\n"
		"        | gpg --dearmor -o /usr/share/keyrings/kitware-archive-keyring.gpg \\\n"
		"    && echo \"deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ noble main\" \\\n"
		"        > /etc/apt/sources.list.d/kitware.list \\\n"
		"    && rm -rf /var/lib/apt/lists/*\n"
		"\n"
		"RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \\\n"
		"        cmake \\\n"
		"        ninja-build \\\n"
		"        build-essential \\\n"
		"        gcc \\\n"
		"        clang \\\n"
		"        wine64 \\\n"
		"        mingw-w64 \\\n"
		"        qemu-user \\\n"
		"        git \\\n"
		"        rsync \\\n"
		"    && rm -rf /var/lib/apt/lists/*\n"
		"\n"
		"RUN set -e; for cc in gcc clang; do \\\n"
		"        command -v \"$cc\" >/dev/null || { echo \"missing reference compiler $cc\"; exit 1; }; \\\n"
		"    done; echo \"reference compilers present (gcc + clang)\"; \\\n"
		"    cmake --version | head -1\n"
		"\n"
		"RUN useradd --create-home ci \\\n"
		"    && mkdir -p /src /build \\\n"
		"    && chown ci:ci /src /build\n"
		"\n"
		"ENV WINEDEBUG=-all \\\n"
		"    WINEPREFIX=/home/ci/.wine\n"
		"\n"
		"COPY run-ci.sh /usr/local/bin/run-ci\n"
		"RUN chmod +x /usr/local/bin/run-ci\n"
		"\n"
		"USER ci\n"
		"WORKDIR /work\n"
		"ENTRYPOINT [\"/usr/local/bin/run-ci\"]\n"
		"";

static const char TMPL_QEMU_DOCKERFILE[] =
		"FROM debian:stable-slim\n"
		"\n"
		"RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \\\n"
		"        build-essential \\\n"
		"        cmake \\\n"
		"        ninja-build \\\n"
		"        make \\\n"
		"        git \\\n"
		"        ca-certificates \\\n"
		"        curl \\\n"
		"        qemu-user \\\n"
		"        tar \\\n"
		"        xz-utils \\\n"
		"        bzip2 \\\n"
		"        rsync \\\n"
		"        clang \\\n"
		"        lld \\\n"
		"    && rm -rf /var/lib/apt/lists/*\n"
		"\n"
		"RUN set -e; for q in @QEMUBINS@; do \\\n"
		"        command -v \"$q\" >/dev/null || { echo \"missing $q\"; exit 1; }; \\\n"
		"    done; echo \"qemu-user emulators present\"; \\\n"
		"    for cc in gcc clang; do \\\n"
		"        command -v \"$cc\" >/dev/null || { echo \"missing diff3 reference $cc\"; exit 1; }; \\\n"
		"    done; echo \"diff3 reference compilers present (gcc + clang)\"\n"
		"\n"
		"WORKDIR /work\n"
		"COPY run-matrix.sh /usr/local/bin/run-matrix\n"
		"RUN chmod +x /usr/local/bin/run-matrix\n"
		"ENTRYPOINT [\"/usr/local/bin/run-matrix\"]\n"
		"";

static const char TMPL_RUN_CI_SH[] =
		"#!/usr/bin/env bash\n"
		"set -euo pipefail\n"
		"\n"
		"SRC_MOUNT=/work\n"
		"SRC=/src\n"
		"\n"
		"PRESET=\"${PRESET:?set PRESET to a CMake preset name (e.g. linux-gcc); see CMakePresets.json}\"\n"
		"\n"
		"if [ ! -e \"$SRC_MOUNT/CMakeLists.txt\" ]; then\n"
		"    echo \"error: mount the mcc repo at $SRC_MOUNT (docker run -v \\\"\\$PWD\\\":/work:ro ...)\" >&2\n"
		"    exit 2\n"
		"fi\n"
		"\n"
		"CC=\"${CC:-cc}\"\n"
		"\"$CC\" -O2 -o /tmp/mcc-ci \\\n"
		"    \"$SRC_MOUNT/tools/ci.c\" \"$SRC_MOUNT/tools/toolsupport.c\" -ldl\n"
		"\n"
		"/tmp/mcc-ci stage \"$SRC_MOUNT\" \"$SRC\"\n"
		"\n"
		"# Download-once, share-everywhere: reuse the host's vendor toolchains when the\n"
		"# launcher bind-mounted them at /vendor (staging excludes vendor/ by design).\n"
		"if [ -d /vendor ]; then\n"
		"    ln -sfn /vendor \"$SRC/vendor\"\n"
		"    echo \"==> sharing vendor toolchains from the /vendor mount\"\n"
		"fi\n"
		"\n"
		"cd \"$SRC\"\n"
		"\n"
		"# Install/stage into the shared /dist mount (per-artifact subdir when ART is set),\n"
		"# so build outputs land in the host's dist/ tree — the output counterpart of the\n"
		"# /vendor input mount.\n"
		"DEST=\"/dist${ART:+/$ART}\"\n"
		"if [ -d /dist ] && [ -w /dist ]; then\n"
		"    mkdir -p \"$DEST\"\n"
		"    exec /tmp/mcc-ci run-preset \"$PRESET\" --out \"$DEST\" -- \"$@\"\n"
		"else\n"
		"    exec /tmp/mcc-ci run-preset \"$PRESET\" -- \"$@\"\n"
		"fi\n"
		"";

static const char TMPL_RUN_MATRIX_SH[] =
		"#!/usr/bin/env bash\n"
		"# Docker entrypoint (macOS-friendly wrapper): compile the ci tool, stage the\n"
		"# bind-mounted repo into an internal tree (so no Linux build artifacts leak back\n"
		"# into a read-only / macOS host mount), wire the shared /vendor (inputs) and\n"
		"# /dist (outputs) mounts into it, then hand off to `ci qemu`, which owns the\n"
		"# configure/build/fixup/test steps. Keeping that logic in tools/ci.c lets CI run\n"
		"# the same matrix natively on a Linux runner without Docker (see\n"
		"# .github/workflows/ci.yml). Mirrors tests/ci/docker/run-ci.sh.\n"
		"set -euo pipefail\n"
		"\n"
		"SRC_MOUNT=/work\n"
		"SRC=/src\n"
		"\n"
		"if [ ! -e \"$SRC_MOUNT/CMakeLists.txt\" ]; then\n"
		"    echo \"error: mount the mcc repo at $SRC_MOUNT (docker run -v \\\"\\$PWD\\\":/work ...)\" >&2\n"
		"    exit 2\n"
		"fi\n"
		"\n"
		"CC=\"${CC:-cc}\"\n"
		"\"$CC\" -O2 -o /tmp/mcc-ci \\\n"
		"    \"$SRC_MOUNT/tools/ci.c\" \"$SRC_MOUNT/tools/toolsupport.c\" -ldl\n"
		"/tmp/mcc-ci stage \"$SRC_MOUNT\" \"$SRC\"\n"
		"\n"
		"# Download-once, share-everywhere: point the staged tree's vendor/ (inputs) and\n"
		"# dist/ (outputs) at their bind mounts, so fetched toolchains and produced\n"
		"# artifacts are shared with the host and every container rather than staged.\n"
		"for shared in vendor dist; do\n"
		"    if [ -d \"/$shared\" ]; then\n"
		"        ln -sfn \"/$shared\" \"$SRC/$shared\"\n"
		"        echo \"==> sharing /$shared mount into the staged tree\"\n"
		"    fi\n"
		"done\n"
		"\n"
		"cd \"$SRC\"\n"
		"# Gentoo stage3 rootfs trees are vendored under vendor/ (-> the /vendor mount),\n"
		"# so they are downloaded once and shared with the host and every container.\n"
		"export MCC_QEMU_DLDIR=\"$SRC/vendor\"\n"
		"exec /tmp/mcc-ci qemu \"$@\"\n"
		"";

static const struct {
	const char *path;
	const char *tmpl;
} EMIT_FILES[] = {
		{".github/workflows/ci.yml", TMPL_CI_YML},
		{".github/workflows/dist.yml", TMPL_DIST_YML},
		{".github/workflows/release.yml", TMPL_RELEASE_YML},
		{".github/workflows/bench.yml", TMPL_BENCH_YML},
		{".github/workflows/matrix.yml", TMPL_MATRIX_YML},
		{".github/workflows/fuzz-nightly.yml", TMPL_FUZZ_YML},
		{"tests/ci/docker/Dockerfile", TMPL_CI_DOCKERFILE},
		{"tests/qemu/docker/Dockerfile", TMPL_QEMU_DOCKERFILE},
		{"tests/ci/docker/run-ci.sh", TMPL_RUN_CI_SH},
		{"tests/qemu/docker/run-matrix.sh", TMPL_RUN_MATRIX_SH},
		{0, 0}};

#endif
