if(DEFINED SRCLIST)
	file(STRINGS "${SRCLIST}" SRCS)
endif()
if(NOT DEFINED SRCS)
	message(FATAL_ERROR "run_selfcheck.cmake: SRCS or SRCLIST required")
endif()
list(LENGTH SRCS _nsrc)
if(NOT DEFINED LEVELS)
	set(LEVELS -O0 -O1 -O2 -O3)
endif()

set(ENV{ASAN_OPTIONS} "detect_leaks=0:abort_on_error=0:exitcode=99")
set(ENV{UBSAN_OPTIONS} "halt_on_error=0:print_stacktrace=0")

set(_bad 0)
foreach(_src IN LISTS SRCS)
	foreach(_opt IN LISTS LEVELS)
		set(_inc)
		if(DEFINED IDIR)
			set(_inc "-I${IDIR}")
		endif()
		execute_process(
			COMMAND "${MCC}" "-B${BDIR}" ${_inc} ${_opt} -c "${_src}" -o "${OUT}.o"
			RESULT_VARIABLE _rc OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
		if(_err MATCHES "runtime error|AddressSanitizer|use-after|heap-buffer|stack-buffer|nonnull|SUMMARY: ")
			message(WARNING "sanitizer report: ${_src} ${_opt}\n${_err}")
			set(_bad 1)
		endif()
		if(_rc GREATER_EQUAL 128 OR _rc EQUAL 99)
			message(WARNING "mcc_s crashed on ${_src} ${_opt}: rc=${_rc}\n${_out}${_err}")
			set(_bad 1)
		endif()
	endforeach()
endforeach()

if(_bad)
	message(FATAL_ERROR "mcc_s self-check found sanitizer diagnostics (see warnings above)")
endif()
message(STATUS "mcc_s self-check: ${_nsrc} sources clean across ${LEVELS}")
