DEF(TOK_IF, "if")
DEF(TOK_ELSE, "else")
DEF(TOK_WHILE, "while")
DEF(TOK_FOR, "for")
DEF(TOK_DO, "do")
DEF(TOK_CONTINUE, "continue")
DEF(TOK_BREAK, "break")
DEF(TOK_RETURN, "return")
DEF(TOK_GOTO, "goto")
DEF(TOK_SWITCH, "switch")
DEF(TOK_CASE, "case")
DEF(TOK_DEFAULT, "default")
DEF(TOK_ASM1, "asm")
DEF(TOK_ASM2, "__asm")
DEF(TOK_ASM3, "__asm__")

DEF(TOK_EXTERN, "extern")
DEF(TOK_STATIC, "static")
DEF(TOK_UNSIGNED, "unsigned")
DEF(TOK__Atomic, "_Atomic")
DEF(TOK_CONST1, "const")
DEF(TOK_CONST2, "__const")
DEF(TOK_CONST3, "__const__")
DEF(TOK_VOLATILE1, "volatile")
DEF(TOK_VOLATILE2, "__volatile")
DEF(TOK_VOLATILE3, "__volatile__")
DEF(TOK_REGISTER, "register")
DEF(TOK_SIGNED1, "signed")
DEF(TOK_SIGNED2, "__signed")
DEF(TOK_SIGNED3, "__signed__")
DEF(TOK_AUTO, "auto")
DEF(TOK_AUTO_TYPE, "__auto_type")
DEF(TOK_INLINE1, "inline")
DEF(TOK_INLINE2, "__inline")
DEF(TOK_INLINE3, "__inline__")
DEF(TOK_RESTRICT1, "restrict")
DEF(TOK_RESTRICT2, "__restrict")
DEF(TOK_RESTRICT3, "__restrict__")
DEF(TOK_EXTENSION, "__extension__")
DEF(TOK_THREAD_LOCAL, "_Thread_local")
DEF(TOK___thread, "__thread")
DEF(TOK___try, "__try")
DEF(TOK___except, "__except")
DEF(TOK___finally, "__finally")

DEF(TOK_GENERIC, "_Generic")
DEF(TOK_STATIC_ASSERT, "_Static_assert")

DEF(TOK_VOID, "void")
DEF(TOK_CHAR, "char")
DEF(TOK_INT, "int")
DEF(TOK_FLOAT, "float")
DEF(TOK_DOUBLE, "double")
DEF(TOK_BOOL, "_Bool")
DEF(TOK_INT128, "__int128")
DEF(TOK_INT256, "__int256")
DEF(TOK_FLOAT16, "_Float16")
DEF(TOK_FP16, "__fp16")
DEF(TOK_BFLOAT16, "__bf16")
DEF(TOK_FLOAT128, "__float128")
DEF(TOK_FLOAT128X, "_Float128")
DEF(TOK_FLOAT32, "_Float32")
DEF(TOK_FLOAT64, "_Float64")
DEF(TOK_FLOAT32X, "_Float32x")
DEF(TOK_FLOAT64X, "_Float64x")
DEF(TOK_BITINT, "_BitInt")
DEF(TOK_COMPLEX, "_Complex")
DEF(TOK_COMPLEX2, "__complex")
DEF(TOK_COMPLEX3, "__complex__")
DEF(TOK_IMAGINARY, "_Imaginary")
DEF(TOK_SHORT, "short")
DEF(TOK_LONG, "long")
DEF(TOK_STRUCT, "struct")
DEF(TOK_UNION, "union")
DEF(TOK_TYPEDEF, "typedef")
DEF(TOK_ENUM, "enum")
DEF(TOK_SIZEOF, "sizeof")
DEF(TOK_ATTRIBUTE1, "__attribute")
DEF(TOK_ATTRIBUTE2, "__attribute__")
DEF(TOK_ALIGNOF1, "__alignof")
DEF(TOK_ALIGNOF2, "__alignof__")
DEF(TOK_ALIGNOF3, "_Alignof")
DEF(TOK_ALIGNAS, "_Alignas")
DEF(TOK_COUNTOF, "_Countof")
DEF(TOK_TYPEOF1, "typeof")
DEF(TOK_TYPEOF2, "__typeof")
DEF(TOK_TYPEOF3, "__typeof__")
DEF(TOK_TYPEOF_UNQUAL, "typeof_unqual")
DEF(TOK_REALPART1, "__real")
DEF(TOK_REALPART2, "__real__")
DEF(TOK_IMAGPART1, "__imag")
DEF(TOK_IMAGPART2, "__imag__")
DEF(TOK_LABEL, "__label__")

DEF(TOK_TRANSACTION_ATOMIC, "__transaction_atomic")
DEF(TOK_TRANSACTION_RELAXED, "__transaction_relaxed")
DEF(TOK_TRANSACTION_CANCEL, "__transaction_cancel")

DEF(TOK_DEFINE, "define")
DEF(TOK_INCLUDE, "include")
DEF(TOK_INCLUDE_NEXT, "include_next")
DEF(TOK_IFDEF, "ifdef")
DEF(TOK_IFNDEF, "ifndef")
DEF(TOK_ELIF, "elif")
DEF(TOK_ENDIF, "endif")
DEF(TOK_DEFINED, "defined")
DEF(TOK_UNDEF, "undef")
DEF(TOK_ERROR, "error")
DEF(TOK_WARNING, "warning")
DEF(TOK_LINE, "line")
DEF(TOK_PRAGMA, "pragma")
DEF(TOK__Pragma, "_Pragma")
DEF(TOK___LINE__, "__LINE__")
DEF(TOK___FILE__, "__FILE__")
DEF(TOK___DATE__, "__DATE__")
DEF(TOK___TIME__, "__TIME__")
DEF(TOK___FUNCTION__, "__FUNCTION__")
DEF(TOK___VA_ARGS__, "__VA_ARGS__")
DEF(TOK___COUNTER__, "__COUNTER__")
DEF(TOK___INCLUDE_LEVEL__, "__INCLUDE_LEVEL__")
DEF(TOK___FILE_NAME__, "__FILE_NAME__")
DEF(TOK___TIMESTAMP__, "__TIMESTAMP__")
DEF(TOK___HAS_INCLUDE, "__has_include")
DEF(TOK___HAS_INCLUDE_NEXT, "__has_include_next")
DEF(TOK___HAS_EMBED, "__has_embed")
DEF(TOK_ASSERT, "assert")
DEF(TOK_UNASSERT, "unassert")
DEF(TOK_IMPORT, "import")
DEF(TOK_ELIFDEF, "elifdef")
DEF(TOK_ELIFNDEF, "elifndef")
DEF(TOK_EMBED, "embed")
DEF(TOK_EMBED_LIMIT, "limit")
DEF(TOK_EMBED_PREFIX, "prefix")
DEF(TOK_EMBED_SUFFIX, "suffix")
DEF(TOK_EMBED_IF_EMPTY, "if_empty")
DEF(TOK_EMBED_OFFSET, "offset")
DEF(TOK_KW_GNU, "gnu")
DEF(TOK_CONSTEXPR, "constexpr")
DEF(TOK_NULLPTR, "nullptr")

DEF(TOK___FUNC__, "__func__")

DEF(TOK___NAN__, "__nan__")
DEF(TOK___SNAN__, "__snan__")
DEF(TOK___INF__, "__inf__")

DEF(TOK_SECTION1, "section")
DEF(TOK_SECTION2, "__section__")
DEF(TOK_ALIGNED1, "aligned")
DEF(TOK_ALIGNED2, "__aligned__")
DEF(TOK_PACKED1, "packed")
DEF(TOK_PACKED2, "__packed__")
DEF(TOK_MS_STRUCT1, "ms_struct")
DEF(TOK_MS_STRUCT2, "__ms_struct__")
DEF(TOK_GCC_STRUCT1, "gcc_struct")
DEF(TOK_GCC_STRUCT2, "__gcc_struct__")
DEF(TOK_SCALAR_STORAGE_ORDER1, "scalar_storage_order")
DEF(TOK_SCALAR_STORAGE_ORDER2, "__scalar_storage_order__")
DEF(TOK_TRANSPARENT_UNION1, "transparent_union")
DEF(TOK_TRANSPARENT_UNION2, "__transparent_union__")
DEF(TOK_WEAK1, "weak")
DEF(TOK_WEAK2, "__weak__")
DEF(TOK_ALIAS1, "alias")
DEF(TOK_ALIAS2, "__alias__")
DEF(TOK___ERROR__, "__error__")
DEF(TOK___WARNING__, "__warning__")
DEF(TOK_WEAKREF1, "weakref")
DEF(TOK_WEAKREF2, "__weakref__")
DEF(TOK_USED1, "used")
DEF(TOK_USED2, "__used__")
DEF(TOK_UNUSED1, "unused")
DEF(TOK_UNUSED2, "__unused__")
DEF(TOK_FORMAT1, "format")
DEF(TOK_FORMAT2, "__format__")
DEF(TOK_NODEBUG1, "nodebug")
DEF(TOK_NODEBUG2, "__nodebug__")
DEF(TOK_DEPRECATED1, "deprecated")
DEF(TOK_DEPRECATED2, "__deprecated__")
DEF(TOK_UNAVAILABLE1, "unavailable")
DEF(TOK_UNAVAILABLE2, "__unavailable__")
DEF(TOK_MAYBE_UNUSED1, "maybe_unused")
DEF(TOK_MAYBE_UNUSED2, "__maybe_unused__")
DEF(TOK_NODISCARD1, "nodiscard")
DEF(TOK_NODISCARD2, "__nodiscard__")
DEF(TOK_FALLTHROUGH1, "fallthrough")
DEF(TOK_FALLTHROUGH2, "__fallthrough__")
DEF(TOK_UNSEQUENCED1, "unsequenced")
DEF(TOK_UNSEQUENCED2, "__unsequenced__")
DEF(TOK_REPRODUCIBLE1, "reproducible")
DEF(TOK_REPRODUCIBLE2, "__reproducible__")
DEF(TOK_CDECL1, "cdecl")
DEF(TOK_CDECL2, "__cdecl")
DEF(TOK_CDECL3, "__cdecl__")
DEF(TOK_STDCALL1, "stdcall")
DEF(TOK_STDCALL2, "__stdcall")
DEF(TOK_STDCALL3, "__stdcall__")
DEF(TOK_FASTCALL1, "fastcall")
DEF(TOK_FASTCALL2, "__fastcall")
DEF(TOK_FASTCALL3, "__fastcall__")
DEF(TOK_THISCALL1, "thiscall")
DEF(TOK_THISCALL2, "__thiscall")
DEF(TOK_THISCALL3, "__thiscall__")
DEF(TOK_REGPARM1, "regparm")
DEF(TOK_REGPARM2, "__regparm__")
DEF(TOK_CLEANUP1, "cleanup")
DEF(TOK_CLEANUP2, "__cleanup__")
DEF(TOK_CONSTRUCTOR1, "constructor")
DEF(TOK_CONSTRUCTOR2, "__constructor__")
DEF(TOK_DESTRUCTOR1, "destructor")
DEF(TOK_DESTRUCTOR2, "__destructor__")
DEF(TOK_ALWAYS_INLINE1, "always_inline")
DEF(TOK_ALWAYS_INLINE2, "__always_inline__")
DEF(TOK_NOINLINE, "__noinline__")
DEF(TOK_NOINLINE1, "noinline")
DEF(TOK_GNU_INLINE1, "gnu_inline")
DEF(TOK_GNU_INLINE2, "__gnu_inline__")
DEF(TOK_PURE1, "pure")
DEF(TOK_PURE2, "__pure__")

DEF(TOK_VECTOR_SIZE1, "vector_size")
DEF(TOK_VECTOR_SIZE2, "__vector_size__")
DEF(TOK_MODE1, "mode")
DEF(TOK_MODE2, "__mode__")
DEF(TOK_MODE_QI1, "QI")
DEF(TOK_MODE_QI2, "__QI__")
DEF(TOK_MODE_HI1, "HI")
DEF(TOK_MODE_HI2, "__HI__")
DEF(TOK_MODE_SI1, "SI")
DEF(TOK_MODE_SI2, "__SI__")
DEF(TOK_MODE_DI1, "DI")
DEF(TOK_MODE_DI2, "__DI__")
DEF(TOK_MODE_TI1, "TI")
DEF(TOK_MODE_TI2, "__TI__")
DEF(TOK_MODE_SF1, "SF")
DEF(TOK_MODE_SF2, "__SF__")
DEF(TOK_MODE_DF1, "DF")
DEF(TOK_MODE_DF2, "__DF__")
DEF(TOK_MODE_XF1, "XF")
DEF(TOK_MODE_XF2, "__XF__")
DEF(TOK_MODE_TF1, "TF")
DEF(TOK_MODE_TF2, "__TF__")
DEF(TOK_MODE_word1, "word")
DEF(TOK_MODE_word2, "__word__")
DEF(TOK_MODE_byte1, "byte")
DEF(TOK_MODE_byte2, "__byte__")
DEF(TOK_MODE_pointer1, "pointer")
DEF(TOK_MODE_pointer2, "__pointer__")
DEF(TOK_MODE_unwind_word1, "unwind_word")
DEF(TOK_MODE_unwind_word2, "__unwind_word__")
DEF(TOK_MODE_libgcc_cmp_return1, "libgcc_cmp_return")
DEF(TOK_MODE_libgcc_cmp_return2, "__libgcc_cmp_return__")
DEF(TOK_MODE_libgcc_shift_count1, "libgcc_shift_count")
DEF(TOK_MODE_libgcc_shift_count2, "__libgcc_shift_count__")

DEF(TOK_DLLEXPORT, "dllexport")
DEF(TOK_DLLIMPORT, "dllimport")
DEF(TOK_NODECORATE, "nodecorate")
DEF(TOK_NORETURN1, "noreturn")
DEF(TOK_NORETURN2, "__noreturn__")
DEF(TOK_NORETURN3, "_Noreturn")
DEF(TOK_VISIBILITY1, "visibility")
DEF(TOK_VISIBILITY2, "__visibility__")

DEF(TOK_builtin_types_compatible_p, "__builtin_types_compatible_p")
DEF(TOK_builtin_choose_expr, "__builtin_choose_expr")
DEF(TOK_builtin_constant_p, "__builtin_constant_p")
DEF(TOK_mcc_overflow_p_const, "__mcc_overflow_p_const")
DEF(TOK_builtin_classify_type, "__builtin_classify_type")
DEF(TOK_builtin_bitprecisionof, "__builtin_bitprecisionof")
DEF(TOK_builtin_complex, "__builtin_complex")
DEF(TOK_builtin_frame_address, "__builtin_frame_address")
DEF(TOK_builtin_return_address, "__builtin_return_address")
DEF(TOK_builtin_dwarf_cfa, "__builtin_dwarf_cfa")
DEF(TOK_builtin_dwarf_sp_column, "__builtin_dwarf_sp_column")
DEF(TOK_builtin_expect, "__builtin_expect")
DEF(TOK_builtin_unreachable, "__builtin_unreachable")
DEF(TOK_builtin_prefetch, "__builtin_prefetch")
DEF(TOK_builtin_assume, "__builtin_assume")
DEF(TOK_builtin_assume_aligned, "__builtin_assume_aligned")
DEF(TOK_builtin_trap, "__builtin_trap")
DEF(TOK_builtin_LINE, "__builtin_LINE")
DEF(TOK_builtin_FILE, "__builtin_FILE")
DEF(TOK_builtin_FUNCTION, "__builtin_FUNCTION")
DEF(TOK_builtin_expect_with_probability, "__builtin_expect_with_probability")
DEF(TOK_builtin_object_size, "__builtin_object_size")
DEF(TOK_builtin_shuffle, "__builtin_shuffle")
DEF(TOK_builtin_shufflevector, "__builtin_shufflevector")
DEF(TOK_builtin_convertvector, "__builtin_convertvector")
DEF(TOK_builtin_dynamic_object_size, "__builtin_dynamic_object_size")
DEF(TOK_builtin_speculation_safe_value, "__builtin_speculation_safe_value")
DEF(TOK_builtin_nan, "__builtin_nan")
DEF(TOK_builtin_nanf, "__builtin_nanf")
DEF(TOK_builtin_nanl, "__builtin_nanl")
DEF(TOK_builtin_inf, "__builtin_inf")
DEF(TOK_builtin_inff, "__builtin_inff")
DEF(TOK_builtin_infl, "__builtin_infl")
DEF(TOK_builtin_huge_val, "__builtin_huge_val")
DEF(TOK_builtin_huge_valf, "__builtin_huge_valf")
DEF(TOK_builtin_huge_vall, "__builtin_huge_vall")
DEF(TOK_builtin_nanf16, "__builtin_nanf16")
DEF(TOK_builtin_inff16, "__builtin_inff16")
DEF(TOK_builtin_huge_valf16, "__builtin_huge_valf16")
DEF(TOK_builtin_infq, "__builtin_infq")
DEF(TOK_builtin_huge_valq, "__builtin_huge_valq")
DEF(TOK_builtin_nanq, "__builtin_nanq")
DEF(TOK_builtin_nansq, "__builtin_nansq")
DEF(TOK_builtin_inff128, "__builtin_inff128")
DEF(TOK_builtin_huge_valf128, "__builtin_huge_valf128")
DEF(TOK_builtin_nanf128, "__builtin_nanf128")
DEF(TOK_builtin_nansf128, "__builtin_nansf128")
DEF(TOK_builtin_signbit, "__builtin_signbit")
DEF(TOK_builtin_signbitf, "__builtin_signbitf")
DEF(TOK_builtin_signbitl, "__builtin_signbitl")
DEF(TOK_builtin_fabs, "__builtin_fabs")
DEF(TOK_builtin_fabsf, "__builtin_fabsf")
DEF(TOK_builtin_ffs, "__builtin_ffs")
DEF(TOK_builtin_ffsl, "__builtin_ffsl")
DEF(TOK_builtin_ffsll, "__builtin_ffsll")
DEF(TOK_builtin_clz, "__builtin_clz")
DEF(TOK_builtin_clzl, "__builtin_clzl")
DEF(TOK_builtin_clzll, "__builtin_clzll")
DEF(TOK_builtin_ctz, "__builtin_ctz")
DEF(TOK_builtin_ctzl, "__builtin_ctzl")
DEF(TOK_builtin_ctzll, "__builtin_ctzll")
DEF(TOK_builtin_clrsb, "__builtin_clrsb")
DEF(TOK_builtin_clrsbl, "__builtin_clrsbl")
DEF(TOK_builtin_clrsbll, "__builtin_clrsbll")
DEF(TOK_builtin_popcount, "__builtin_popcount")
DEF(TOK_builtin_popcountl, "__builtin_popcountl")
DEF(TOK_builtin_popcountll, "__builtin_popcountll")
DEF(TOK_builtin_parity, "__builtin_parity")
DEF(TOK_builtin_parityl, "__builtin_parityl")
DEF(TOK_builtin_parityll, "__builtin_parityll")
DEF(TOK_builtin_bswap16, "__builtin_bswap16")
DEF(TOK_builtin_bswap32, "__builtin_bswap32")
DEF(TOK_builtin_bswap64, "__builtin_bswap64")
#if defined MCC_TARGET_PE && defined MCC_TARGET_X86_64
DEF(TOK_builtin_va_start, "__builtin_va_start")
#elif defined MCC_TARGET_X86_64
DEF(TOK_builtin_va_arg_types, "__builtin_va_arg_types")
DEF(TOK_builtin_va_start_check, "__builtin_va_start_check")
#elif defined MCC_TARGET_ARM64
DEF(TOK_builtin_va_start, "__builtin_va_start")
DEF(TOK_builtin_va_arg, "__builtin_va_arg")
#elif defined MCC_TARGET_RISCV64
DEF(TOK_builtin_va_start, "__builtin_va_start")
#endif
#if !defined MCC_TARGET_X86_64 || defined MCC_TARGET_PE
DEF(TOK_builtin_c23_va_start, "__builtin_c23_va_start")
#endif

#define DEF_ATOMIC(ID) DEF(TOK_##__##ID, "__" #ID)
DEF_ATOMIC(atomic_store)
DEF_ATOMIC(atomic_load)
DEF_ATOMIC(atomic_exchange)
DEF_ATOMIC(atomic_compare_exchange)
DEF_ATOMIC(atomic_fetch_add)
DEF_ATOMIC(atomic_fetch_sub)
DEF_ATOMIC(atomic_fetch_or)
DEF_ATOMIC(atomic_fetch_xor)
DEF_ATOMIC(atomic_fetch_and)
DEF_ATOMIC(atomic_fetch_nand)
DEF_ATOMIC(atomic_add_fetch)
DEF_ATOMIC(atomic_sub_fetch)
DEF_ATOMIC(atomic_or_fetch)
DEF_ATOMIC(atomic_xor_fetch)
DEF_ATOMIC(atomic_and_fetch)
DEF_ATOMIC(atomic_nand_fetch)

DEF(TOK_pack, "pack")
#if !defined(MCC_TARGET_I386) && !defined(MCC_TARGET_X86_64) && \
		!defined(MCC_TARGET_ARM) && !defined(MCC_TARGET_ARM64) &&   \
		!defined(MCC_TARGET_RISCV64)
DEF(TOK_ASM_push, "push")
DEF(TOK_ASM_pop, "pop")
#endif
DEF(TOK_comment, "comment")
DEF(TOK_lib, "lib")
DEF(TOK_push_macro, "push_macro")
DEF(TOK_pop_macro, "pop_macro")
DEF(TOK_once, "once")
DEF(TOK_option, "option")
DEF(TOK_STDC, "STDC")
DEF(TOK_pragma_message, "message")

DEF(TOK___mcc_i256_add, "__mcc_i256_add")
DEF(TOK___mcc_i256_sub, "__mcc_i256_sub")
DEF(TOK___mcc_i256_mul, "__mcc_i256_mul")
DEF(TOK___mcc_i256_and, "__mcc_i256_and")
DEF(TOK___mcc_i256_or, "__mcc_i256_or")
DEF(TOK___mcc_i256_xor, "__mcc_i256_xor")
DEF(TOK___mcc_i256_shl, "__mcc_i256_shl")
DEF(TOK___mcc_i256_shr, "__mcc_i256_shr")
DEF(TOK___mcc_i256_sar, "__mcc_i256_sar")
DEF(TOK___mcc_i256_udiv, "__mcc_i256_udiv")
DEF(TOK___mcc_i256_sdiv, "__mcc_i256_sdiv")
DEF(TOK___mcc_i256_umod, "__mcc_i256_umod")
DEF(TOK___mcc_i256_smod, "__mcc_i256_smod")
DEF(TOK___mcc_i256_ucmp, "__mcc_i256_ucmp")
DEF(TOK___mcc_i256_scmp, "__mcc_i256_scmp")
DEF(TOK___mcc_i256_to_f64, "__mcc_i256_to_f64")
DEF(TOK___mcc_i256_to_f32, "__mcc_i256_to_f32")
DEF(TOK___mcc_i256_from_f64, "__mcc_i256_from_f64")
DEF(TOK___mcc_i256_from_f32, "__mcc_i256_from_f32")

DEF(TOK___mcc_i512_add, "__mcc_i512_add")
DEF(TOK___mcc_i512_sub, "__mcc_i512_sub")
DEF(TOK___mcc_i512_mul, "__mcc_i512_mul")
DEF(TOK___mcc_i512_and, "__mcc_i512_and")
DEF(TOK___mcc_i512_or, "__mcc_i512_or")
DEF(TOK___mcc_i512_xor, "__mcc_i512_xor")
DEF(TOK___mcc_i512_shl, "__mcc_i512_shl")
DEF(TOK___mcc_i512_shr, "__mcc_i512_shr")
DEF(TOK___mcc_i512_sar, "__mcc_i512_sar")
DEF(TOK___mcc_i512_udiv, "__mcc_i512_udiv")
DEF(TOK___mcc_i512_sdiv, "__mcc_i512_sdiv")
DEF(TOK___mcc_i512_umod, "__mcc_i512_umod")
DEF(TOK___mcc_i512_smod, "__mcc_i512_smod")
DEF(TOK___mcc_i512_ucmp, "__mcc_i512_ucmp")
DEF(TOK___mcc_i512_scmp, "__mcc_i512_scmp")
DEF(TOK___mcc_i512_to_f64, "__mcc_i512_to_f64")
DEF(TOK___mcc_i512_to_f32, "__mcc_i512_to_f32")
DEF(TOK___mcc_i512_from_f64, "__mcc_i512_from_f64")
DEF(TOK___mcc_i512_from_f32, "__mcc_i512_from_f32")
#ifndef MCC_ARM_EABI
DEF(TOK_memcpy, "memcpy")
DEF(TOK_memmove, "memmove")
DEF(TOK_memset, "memset")
DEF(TOK___divdi3, "__divdi3")
DEF(TOK___moddi3, "__moddi3")
DEF(TOK___udivdi3, "__udivdi3")
DEF(TOK___umoddi3, "__umoddi3")
DEF(TOK___mcc_umulh64, "__mcc_umulh64")
DEF(TOK___mcc_smulh64, "__mcc_smulh64")
DEF(TOK___multi3, "__multi3")
DEF(TOK___divti3, "__divti3")
DEF(TOK___modti3, "__modti3")
DEF(TOK___udivti3, "__udivti3")
DEF(TOK___umodti3, "__umodti3")
DEF(TOK___ashrti3, "__ashrti3")
DEF(TOK___lshrti3, "__lshrti3")
DEF(TOK___ashlti3, "__ashlti3")
DEF(TOK___floattisf, "__floattisf")
DEF(TOK___floattidf, "__floattidf")
DEF(TOK___floattixf, "__floattixf")
DEF(TOK___floatuntisf, "__floatuntisf")
DEF(TOK___floatuntidf, "__floatuntidf")
DEF(TOK___floatuntixf, "__floatuntixf")
DEF(TOK___fixsfti, "__fixsfti")
DEF(TOK___fixdfti, "__fixdfti")
DEF(TOK___fixxfti, "__fixxfti")
DEF(TOK___fixunssfti, "__fixunssfti")
DEF(TOK___fixunsdfti, "__fixunsdfti")
DEF(TOK___fixunsxfti, "__fixunsxfti")
DEF(TOK___ashrdi3, "__ashrdi3")
DEF(TOK___lshrdi3, "__lshrdi3")
DEF(TOK___ashldi3, "__ashldi3")
DEF(TOK___floatundisf, "__floatundisf")
DEF(TOK___floatundidf, "__floatundidf")
#ifndef MCC_ARM_VFP
DEF(TOK___floatundixf, "__floatundixf")
DEF(TOK___fixunsxfdi, "__fixunsxfdi")
#endif
DEF(TOK___fixunssfdi, "__fixunssfdi")
DEF(TOK___fixunsdfdi, "__fixunsdfdi")
#endif

DEF(TOK___extendhfsf2, "__mcc_extendhfsf2")
DEF(TOK___truncsfhf2, "__mcc_truncsfhf2")
DEF(TOK___extendbfsf2, "__mcc_extendbfsf2")
DEF(TOK___truncsfbf2, "__mcc_truncsfbf2")

#if defined MCC_TARGET_ARM
#ifdef MCC_ARM_EABI
DEF(TOK_memcpy, "__aeabi_memcpy")
DEF(TOK_memmove, "__aeabi_memmove")
DEF(TOK_memmove4, "__aeabi_memmove4")
DEF(TOK_memmove8, "__aeabi_memmove8")
DEF(TOK_memset, "__aeabi_memset")
DEF(TOK___aeabi_ldivmod, "__aeabi_ldivmod")
DEF(TOK___aeabi_uldivmod, "__aeabi_uldivmod")
DEF(TOK___aeabi_idivmod, "__aeabi_idivmod")
DEF(TOK___aeabi_uidivmod, "__aeabi_uidivmod")
DEF(TOK___divsi3, "__aeabi_idiv")
DEF(TOK___udivsi3, "__aeabi_uidiv")
DEF(TOK___floatdisf, "__aeabi_l2f")
DEF(TOK___floatdidf, "__aeabi_l2d")
DEF(TOK___fixsfdi, "__aeabi_f2lz")
DEF(TOK___fixdfdi, "__aeabi_d2lz")
DEF(TOK___ashrdi3, "__aeabi_lasr")
DEF(TOK___lshrdi3, "__aeabi_llsr")
DEF(TOK___ashldi3, "__aeabi_llsl")
DEF(TOK___floatundisf, "__aeabi_ul2f")
DEF(TOK___floatundidf, "__aeabi_ul2d")
DEF(TOK___fixunssfdi, "__aeabi_f2ulz")
DEF(TOK___fixunsdfdi, "__aeabi_d2ulz")
#else
DEF(TOK___modsi3, "__modsi3")
DEF(TOK___umodsi3, "__umodsi3")
DEF(TOK___divsi3, "__divsi3")
DEF(TOK___udivsi3, "__udivsi3")
DEF(TOK___floatdisf, "__floatdisf")
DEF(TOK___floatdidf, "__floatdidf")
#ifndef MCC_ARM_VFP
DEF(TOK___floatdixf, "__floatdixf")
DEF(TOK___fixunssfsi, "__fixunssfsi")
DEF(TOK___fixunsdfsi, "__fixunsdfsi")
DEF(TOK___fixunsxfsi, "__fixunsxfsi")
DEF(TOK___fixxfdi, "__fixxfdi")
#endif
DEF(TOK___fixsfdi, "__fixsfdi")
DEF(TOK___fixdfdi, "__fixdfdi")
#endif
#endif

#if defined MCC_TARGET_I386
DEF(TOK___fixsfdi, "__fixsfdi")
DEF(TOK___fixdfdi, "__fixdfdi")
DEF(TOK___fixxfdi, "__fixxfdi")
#endif
#if defined MCC_TARGET_X86_64
DEF(TOK___fixxfdi, "__fixxfdi")
#endif

DEF(TOK_alloca, "alloca")
DEF(TOK___stack_chk_fail, "__stack_chk_fail")
DEF(TOK___stack_chk_guard, "__stack_chk_guard")

#if defined MCC_TARGET_PE
DEF(TOK___chkstk, "__chkstk")
#endif
#ifdef MCC_TARGET_ARM64
DEF(TOK___arm64_clear_cache, "__arm64_clear_cache")
#endif
#ifdef MCC_TARGET_RISCV64
DEF(TOK___riscv64_clear_cache, "__riscv64_clear_cache")
#endif
#if defined MCC_TARGET_ARM64 || defined MCC_TARGET_RISCV64 || \
	(defined MCC_TARGET_X86_64 && !defined MCC_TARGET_PE)
DEF(TOK___addtf3, "__addtf3")
DEF(TOK___subtf3, "__subtf3")
DEF(TOK___multf3, "__multf3")
DEF(TOK___divtf3, "__divtf3")
DEF(TOK___extendsftf2, "__extendsftf2")
DEF(TOK___extenddftf2, "__extenddftf2")
DEF(TOK___trunctfsf2, "__trunctfsf2")
DEF(TOK___trunctfdf2, "__trunctfdf2")
DEF(TOK___negtf2, "__negtf2")
DEF(TOK___fixtfsi, "__fixtfsi")
DEF(TOK___fixtfdi, "__fixtfdi")
DEF(TOK___fixunstfsi, "__fixunstfsi")
DEF(TOK___fixunstfdi, "__fixunstfdi")
DEF(TOK___floatsitf, "__floatsitf")
DEF(TOK___floatditf, "__floatditf")
DEF(TOK___floatunsitf, "__floatunsitf")
DEF(TOK___floatunditf, "__floatunditf")
DEF(TOK___eqtf2, "__eqtf2")
DEF(TOK___netf2, "__netf2")
DEF(TOK___lttf2, "__lttf2")
DEF(TOK___letf2, "__letf2")
DEF(TOK___gttf2, "__gttf2")
DEF(TOK___getf2, "__getf2")
#endif

DEF(TOK___bound_ptr_add, "__bound_ptr_add")
DEF(TOK___bound_ptr_indir1, "__bound_ptr_indir1")
DEF(TOK___bound_ptr_indir2, "__bound_ptr_indir2")
DEF(TOK___bound_ptr_indir4, "__bound_ptr_indir4")
DEF(TOK___bound_ptr_indir8, "__bound_ptr_indir8")
DEF(TOK___bound_ptr_indir12, "__bound_ptr_indir12")
DEF(TOK___bound_ptr_indir16, "__bound_ptr_indir16")
DEF(TOK___bound_main_arg, "__bound_main_arg")
DEF(TOK___bound_local_new, "__bound_local_new")
DEF(TOK___bound_local_delete, "__bound_local_delete")
DEF(TOK___bound_setjmp, "__bound_setjmp")
DEF(TOK___bound_longjmp, "__bound_longjmp")
DEF(TOK___bound_new_region, "__bound_new_region")
#ifdef MCC_TARGET_PE
#ifdef MCC_TARGET_X86_64
DEF(TOK___bound_alloca_nr, "__bound_alloca_nr")
#endif
#else
DEF(TOK_sigsetjmp, "sigsetjmp")
DEF(TOK___sigsetjmp, "__sigsetjmp")
DEF(TOK_siglongjmp, "siglongjmp")
#endif
DEF(TOK_setjmp, "setjmp")
DEF(TOK__setjmp, "_setjmp")
DEF(TOK_longjmp, "longjmp")

#define DEF_ASM(x) DEF(TOK_ASM_##x, #x)
#define DEF_ASMDIR(x) DEF(TOK_ASMDIR_##x, "." #x)
#define TOK_ASM_int TOK_INT

#define TOK_ASMDIR_FIRST TOK_ASMDIR_byte
#define TOK_ASMDIR_LAST TOK_ASMDIR_section

DEF_ASMDIR(byte)
DEF_ASMDIR(word)
DEF_ASMDIR(align)
DEF_ASMDIR(balign)
DEF_ASMDIR(p2align)
DEF_ASMDIR(set)
DEF_ASMDIR(equ)
DEF_ASMDIR(equiv)
DEF_ASMDIR(comm)
DEF_ASMDIR(lcomm)
DEF_ASMDIR(if)
DEF_ASMDIR(ifdef)
DEF_ASMDIR(ifndef)
DEF_ASMDIR(ifeq)
DEF_ASMDIR(ifne)
DEF_ASMDIR(ifgt)
DEF_ASMDIR(iflt)
DEF_ASMDIR(ifge)
DEF_ASMDIR(ifle)
DEF_ASMDIR(ifc)
DEF_ASMDIR(ifnc)
DEF_ASMDIR(ifb)
DEF_ASMDIR(ifnb)
DEF_ASMDIR(elseif)
DEF_ASMDIR(else)
DEF_ASMDIR(endif)
DEF_ASMDIR(skip)
DEF_ASMDIR(space)
DEF_ASMDIR(zero)
DEF_ASMDIR(string)
DEF_ASMDIR(asciz)
DEF_ASMDIR(ascii)
DEF_ASMDIR(file)
DEF_ASMDIR(globl)
DEF_ASMDIR(global)
DEF_ASMDIR(weak)
DEF_ASMDIR(hidden)
DEF_ASMDIR(ident)
DEF_ASMDIR(size)
DEF_ASMDIR(type)
DEF_ASMDIR(text)
DEF_ASMDIR(data)
DEF_ASMDIR(bss)
DEF_ASMDIR(previous)
DEF_ASMDIR(pushsection)
DEF_ASMDIR(popsection)
DEF_ASMDIR(fill)
DEF_ASMDIR(rept)
DEF_ASMDIR(endr)
DEF_ASMDIR(org)
DEF_ASMDIR(quad)
DEF_ASMDIR(hword)
DEF_ASMDIR(value)
DEF_ASMDIR(xword)
DEF_ASMDIR(2byte)
DEF_ASMDIR(4byte)
DEF_ASMDIR(8byte)
DEF_ASMDIR(float)
DEF_ASMDIR(double)
DEF_ASMDIR(octa)
DEF_ASMDIR(arch)
DEF_ASMDIR(cpu)
DEF_ASMDIR(macro)
DEF_ASMDIR(endm)
DEF_ASMDIR(irp)
#if MCC_PTR_SIZE == 4
DEF_ASMDIR(code16)
DEF_ASMDIR(code32)
#else
DEF_ASMDIR(code64)
#endif
#if defined(MCC_TARGET_RISCV64)
DEF_ASMDIR(option)
#endif
DEF_ASMDIR(short)
DEF_ASMDIR(long)
DEF_ASMDIR(int)
DEF_ASMDIR(symver)
DEF_ASMDIR(reloc)
DEF_ASMDIR(section)

#if defined MCC_TARGET_I386 || defined MCC_TARGET_X86_64
#include "i386-tok.h"
#endif

#if defined MCC_TARGET_ARM
#include "arm-tok.h"
#endif

#if defined MCC_TARGET_ARM64
#include "arm64-tok.h"
#endif

#if defined MCC_TARGET_RISCV64
#include "riscv64-tok.h"
#endif
