#!/usr/bin/env python3
"""cover3.py -- the 3-way covering array over the -f surface in src/mccopt.h.

    cover3.py gen     [cover3.txt]   regenerate the array from the live table
    cover3.py verify  [cover3.txt]   prove the checked-in array still covers

WHAT THIS IS AND IS NOT. Exhaustive three-deep coverage of 115 binary flags is
C(115,3) * 2^3 = 1,975,240 configurations. This is a covering array instead: a
set of rows such that for EVERY choice of three flags and EVERY one of their
eight on/off settings, at least one row contains that setting. That is the same
3-wise guarantee -- any bug that needs no more than three specific flags at
specific settings appears in at least one row -- in ~40 rows instead of ~2M. It
is NOT exhaustive: a bug that needs four or more specific flags can hide.

The construction is IPOG (Lei et al., In-Parameter-Order General), horizontal
growth then vertical growth, with every tie broken toward the lower value and
the earlier row. There is no RNG anywhere, seeded or otherwise: the same table
produces the same file byte for byte, on any host, in any Python 3.

`verify` does not trust `gen`. It re-derives the flag list from mccopt.h, checks
the file names the same flags in the same order, checks each pinned column is
actually constant, and then walks all C(k,3)*8 triples over the varying columns
and reports the first one no row covers. A generator bug, a hand edit, or a new
MCC_OPT_ROW that nobody regenerated for all come out as a failing test.

PINS. A pinned flag is held at one value in every row and contributes no 3-way
variation. Pins exist because the flag is known to produce a wrong program at
the other setting -- an array that is red before it starts cannot report a
regression. Every pin carries its reason in the file and each one is a debt,
not a decision.
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
MCCOPT = os.path.join(ROOT, "src", "mccopt.h")
DEFAULT_OUT = os.path.join(HERE, "cover3.txt")

STRENGTH = 3

PINS = {
    "jit-splice": (
        0, "miscompiles-programs/random_stuff-at-O2; OFF in mccopt.h for that reason"),
    "replay-fallback": (
        1, "-fno-replay-fallback+-fno-replay-cmp-materialize-inverts-comparisons;"
           "see-docs/TODO.md-C2-gap"),
}


def table_flags(path=MCCOPT):
    """The -f names, in MCC_OPT_LIST order. The order is the column order."""
    out = []
    with open(path, "r") as fh:
        for line in fh:
            s = line.strip()
            if not s.startswith("MCC_OPT_ROW("):
                continue
            head, _, rest = s.partition('"')
            name, _, _ = rest.partition('"')
            if name:
                out.append(name)
    return out


def ipog(k, t=STRENGTH):
    """Rows over k binary factors covering every t-way setting. Deterministic."""
    if k <= t:
        return [[(i >> (k - 1 - j)) & 1 for j in range(k)] for i in range(1 << k)]

    rows = [[(i >> (t - 1 - j)) & 1 for j in range(t)] for i in range(1 << t)]

    for p in range(t, k):
        pairs = [(a, b) for a in range(p) for b in range(a + 1, p)]
        uncovered = set()
        for (a, b) in pairs:
            for m in range(8):
                uncovered.add((a, b, (m >> 2) & 1, (m >> 1) & 1, m & 1))

        for row in rows:
            best_val, best_gain, best_hits = 0, -1, None
            for val in (0, 1):
                hits = []
                for (a, b) in pairs:
                    ra, rb = row[a], row[b]
                    if ra is None or rb is None:
                        continue
                    key = (a, b, ra, rb, val)
                    if key in uncovered:
                        hits.append(key)
                if len(hits) > best_gain:
                    best_val, best_gain, best_hits = val, len(hits), hits
            row.append(best_val)
            uncovered.difference_update(best_hits)

        for key in sorted(uncovered):
            a, b, va, vb, vp = key
            placed = False
            for row in rows:
                if row[a] in (None, va) and row[b] in (None, vb) and row[p] in (None, vp):
                    row[a], row[b], row[p] = va, vb, vp
                    placed = True
                    break
            if not placed:
                row = [None] * (p + 1)
                row[a], row[b], row[p] = va, vb, vp
                rows.append(row)

    return [[0 if v is None else v for v in row] for row in rows]


def build(path_out):
    flags = table_flags()
    vary = [f for f in flags if f not in PINS]
    idx_of_vary = {f: i for i, f in enumerate(vary)}
    rows = ipog(len(vary))

    lines = []
    lines.append("#! cover3 v1 strength=%d levels=2 flags=%d vary=%d rows=%d"
                 % (STRENGTH, len(flags), len(vary), len(rows)))
    lines.append("#! generated by tests/optfire/cover3.py gen -- do not hand-edit")
    lines.append("#! deterministic IPOG, no RNG; regenerate whenever src/mccopt.h changes")
    lines.append("#! a row is one -f configuration: char i is the setting of flag i")
    for i, f in enumerate(flags):
        if f in PINS:
            lines.append("flag %d %s pin%d %s" % (i, f, PINS[f][0], PINS[f][1]))
        else:
            lines.append("flag %d %s vary -" % (i, f))
    lines.append("rows %d %d" % (len(rows), len(flags)))
    for n, row in enumerate(rows):
        bits = "".join(
            str(PINS[f][0]) if f in PINS else str(row[idx_of_vary[f]]) for f in flags)
        lines.append("row %d %s" % (n, bits))

    with open(path_out, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    return len(rows), len(vary), len(flags)


def load(path_in):
    flags, roles, rows = [], [], []
    with open(path_in, "r") as fh:
        for line in fh:
            s = line.rstrip("\n")
            if s.startswith("#") or not s.strip():
                continue
            parts = s.split()
            if parts[0] == "flag":
                flags.append(parts[2])
                roles.append(parts[3])
            elif parts[0] == "row":
                rows.append(parts[2])
    return flags, roles, rows


def verify(path_in):
    live = table_flags()
    flags, roles, rows = load(path_in)
    bad = 0

    if flags != live:
        missing = [f for f in live if f not in flags]
        stale = [f for f in flags if f not in live]
        print("FAIL cover3: the array does not match src/mccopt.h")
        if missing:
            print("  flags in the table, absent from the array: %s" % " ".join(missing))
        if stale:
            print("  flags in the array, absent from the table: %s" % " ".join(stale))
        if not missing and not stale:
            print("  same flags, different order -- column order is load-bearing")
        print("  regenerate: tests/optfire/cover3.py gen")
        return 1

    k = len(flags)
    for n, bits in enumerate(rows):
        if len(bits) != k:
            print("FAIL cover3: row %d has %d columns, expected %d" % (n, len(bits), k))
            bad += 1
        if set(bits) - set("01"):
            print("FAIL cover3: row %d is not a 0/1 string" % n)
            bad += 1
    if bad:
        return 1

    n_rows = len(rows)
    all_mask = (1 << n_rows) - 1
    ones = [0] * k
    for n, bits in enumerate(rows):
        for j, c in enumerate(bits):
            if c == "1":
                ones[j] |= 1 << n
    zeros = [all_mask & ~o for o in ones]

    for j, role in enumerate(roles):
        if role == "vary":
            continue
        want = 1 if role == "pin1" else 0
        got = ones[j] if want else zeros[j]
        if got != all_mask:
            print("FAIL cover3: %s is pinned %s but varies across rows" % (flags[j], role))
            bad += 1
    if bad:
        return 1

    cols = [j for j, r in enumerate(roles) if r == "vary"]
    kv = len(cols)
    checked = 0
    for ia in range(kv):
        a = cols[ia]
        a0, a1 = zeros[a], ones[a]
        for ib in range(ia + 1, kv):
            b = cols[ib]
            b0, b1 = zeros[b], ones[b]
            p00, p01, p10, p11 = a0 & b0, a0 & b1, a1 & b0, a1 & b1
            for ic in range(ib + 1, kv):
                c = cols[ic]
                c0, c1 = zeros[c], ones[c]
                checked += 8
                if (p00 & c0) and (p00 & c1) and (p01 & c0) and (p01 & c1) \
                   and (p10 & c0) and (p10 & c1) and (p11 & c0) and (p11 & c1):
                    continue
                for m in range(8):
                    ma = a1 if (m >> 2) & 1 else a0
                    mb = b1 if (m >> 1) & 1 else b0
                    mc = c1 if m & 1 else c0
                    if not (ma & mb & mc):
                        print("FAIL cover3: no row sets %s=%d %s=%d %s=%d"
                              % (flags[a], (m >> 2) & 1, flags[b], (m >> 1) & 1,
                                 flags[c], m & 1))
                        bad += 1
                        if bad > 8:
                            print("FAIL cover3: ... stopping after %d uncovered triples" % bad)
                            return 1

    if bad:
        return 1
    pinned = [flags[j] for j, r in enumerate(roles) if r != "vary"]
    print("PASS cover3: %d rows cover all %d 3-way settings of %d flags"
          % (n_rows, checked, kv))
    if pinned:
        print("PASS cover3: %d flag(s) pinned, not covered: %s" % (len(pinned), " ".join(pinned)))
    return 0


def main(argv):
    mode = argv[1] if len(argv) > 1 else ""
    path = argv[2] if len(argv) > 2 else DEFAULT_OUT
    if mode == "gen":
        n, kv, kt = build(path)
        print("wrote %s: %d rows, %d varying flags of %d" % (path, n, kv, kt))
        return verify(path)
    if mode == "verify":
        return verify(path)
    sys.stderr.write("usage: cover3.py gen|verify [cover3.txt]\n")
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv))
